### ISSUE TITLE
Passing "localeIdentifier" to placemarkFromCoordinates function is not working

### ISSUE THREAD

**Issue by ashourms** [Baseflow/flutter-geocoding#10]
## 🐛 Bug Report

Hi,
I am trying to retrieve a place mark details using the function **placemarkFromCoordinates** providing the required **latitude**, **longitude** and the **localeIdentifier** which is basically 'ar_SA' for Arabic language. However, for some reason it is not working. The function will always return the English address regardless of the passed **localeIdentifier** value

### Expected behavior
When passing localeIdentifier, the function should return the place mark details in the specified language

### Configuration
Flutter Version: Channel stable, 1.20.3, 
OS: Mac OS X 10.15.6 19G2021
IOS 13

**Version:** 1.0.3
**Platform:** 
- [X] :iphone: iOS
- [X] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @ashourms, thank you for submitting this issue. There is indeed a small issue passing a long the `localeIdentifier` from the Dart to the native code. 

I will fix this today and send out a hotfix release. Will keep you updated through this ticket

**Comment by mvanbeusekom** [comment]
@ashourms this issue is fixed with the latest hotfix 1.0.3+1. Thanks for reporting!

**Comment by ashourms** [comment]
Thanks for your swift response!

**Comment by fanzibin** [comment]
Hi, I am trying to retrieve a place mark details using the function placemarkFromCoordinates providing the required latitude, longitude and the localeIdentifier,BUT, when I set localeIdentifier to en_US, it is not efficient.

MethodCallHandlerImpl.java

private void onPlacemarkFromCoordinates(MethodCall call, Result result) {
        final double latitude = call.argument("latitude");
        final double longitude = call.argument("longitude");
        final String languageTag = call.argument("localeIdentifier");

the languageTag  return  null

**Comment by fanzibin** [comment]
> Thanks for your swift response!

Hi, I am trying to retrieve a place mark details using the function placemarkFromCoordinates providing the required latitude, longitude and the localeIdentifier,BUT, when I set localeIdentifier to en_US, it is not efficient.

MethodCallHandlerImpl.java

private void onPlacemarkFromCoordinates(MethodCall call, Result result) {
final double latitude = call.argument("latitude");
final double longitude = call.argument("longitude");
final String languageTag = call.argument("localeIdentifier");

the languageTag return null

**Comment by fanzibin** [comment]
> @ashourms this issue is fixed with the latest hotfix 1.0.3+1. Thanks for reporting!

geocoding: ^1.0.5
platform: Android8.1 real
List<Placemark> placemarks  = await placemarkFromCoordinates(52.2165157,6.9437819,localeIdentifier: 'en');
    print('placemarks === $placemarks');

I/flutter (13301): placemarks === [      Name: ,
I/flutter (13301):       Street: 荷兰上艾瑟尔省Waterlelielaan24,
I/flutter (13301):       ISO Country Code: NL,
I/flutter (13301):       Country: 荷兰,
I/flutter (13301):       Postal code: ,
I/flutter (13301):       Administrative area: 上艾瑟尔省,
I/flutter (13301):       Subadministrative area: ,
I/flutter (13301):       Locality: 上艾瑟尔省,
I/flutter (13301):       Sublocality: ,
I/flutter (13301):       Thoroughfare: Waterlelielaan,
I/flutter (13301):       Subthoroughfare: 24]

the result is not english

**Comment by firelonely** [comment]
@mvanbeusekom I use version 2.0.0 and I ran into the same problem！

**Comment by HuberyYang** [comment]
> @mvanbeusekom I use version 2.0.0 and I ran into the same problem！

I also encountered this problem in 2.0.1
