### ISSUE TITLE
Flutter UIAlertView is deprecated

### ISSUE THREAD

**Issue by im-pch** [Baseflow/flutter-geocoding#108]
Issue running on ios simulator after flutter upgrade 2 days ago, was working fine before: 

Last login: Wed Sep 28 19:17:08 on ttys117
rohan@Rohans-Air jakstatcourier % flutter clean && flutter run -d 3D3
Cleaning Xcode workspace...                                        14.3s
Cleaning Xcode workspace...                                         6.6s
Deleting build...                                                  167ms
Deleting .dart_tool...                                               2ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting Flutter.podspec...                                          0ms
Deleting ephemeral...                                                0ms
Deleting ephemeral...                                                0ms
Deleting ephemeral...                                                0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Running "flutter pub get" in jakstatcourier...                   1,521ms
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...                                             10.6s
Running Xcode build...                                                  
Xcode build done.                                           351.7s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[2932]: Class AMSupportURLConnectionDelegate is implemented in both
    /usr/lib/libauthinstall.dylib (0x2051e7ad8) and
    /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDe
    vice (0x10e52c2c8). One of the two will be used. Which one is undefined.
    objc[2932]: Class AMSupportURLSession is implemented in both
    /usr/lib/libauthinstall.dylib (0x2051e7b28) and
    /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDe
    vice (0x10e52c318). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **

Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/dt/ymx6cbj16xq_flrs8l2xzc9r0000gn/T/flutter_tools.rzO49o/flutt
    	er_ios_build_temp_dirHHxj9c/temporary_xcresult_bundle

    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/ios/Classes/L
    ocationPlugin.m:176:13: warning: 'UIAlertView' is deprecated: first
    deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController
    with a preferredStyle of UIAlertControllerStyleAlert instead
    [-Wdeprecated-declarations]
                UIAlertView *alert = [[UIAlertView alloc]
                initWithTitle:@"Location is Disabled"
                ^
    In module 'UIKit' imported from
    /Users/rohan/Downloads/jakstatcourier/ios/Pods/Target Support
    Files/location/location-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/UIKit.fra
    mework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly
    marked deprecated here
    @interface UIAlertView : UIView
               ^
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/ios/Classes/L
    ocationPlugin.m:176:48: warning: 'UIAlertView' is deprecated: first
    deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController
    with a preferredStyle of UIAlertControllerStyleAlert instead
    [-Wdeprecated-declarations]
                UIAlertView *alert = [[UIAlertView alloc]
                initWithTitle:@"Location is Disabled"
                                                   ^
    In module 'UIKit' imported from
    /Users/rohan/Downloads/jakstatcourier/ios/Pods/Target Support
    Files/location/location-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/UIKit.fra
    mework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly
    marked deprecated here
    @interface UIAlertView : UIView
               ^
    2 warnings generated.
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/ios/Classes/L
    ocationPlugin.m:176:13: warning: 'UIAlertView' is deprecated: first
    deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController
    with a preferredStyle of UIAlertControllerStyleAlert instead
    [-Wdeprecated-declarations]
                UIAlertView *alert = [[UIAlertView alloc]
                initWithTitle:@"Location is Disabled"
                ^
    In module 'UIKit' imported from
    /Users/rohan/Downloads/jakstatcourier/ios/Pods/Target Support
    Files/location/location-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/UIKit.fra
    mework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly
    marked deprecated here
    @interface UIAlertView : UIView
               ^
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/ios/Classes/L
    ocationPlugin.m:176:48: warning: 'UIAlertView' is deprecated: first
    deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController
    with a preferredStyle of UIAlertControllerStyleAlert instead
    [-Wdeprecated-declarations]
                UIAlertView *alert = [[UIAlertView alloc]
                initWithTitle:@"Location is Disabled"
                                                   ^
    In module 'UIKit' imported from
    /Users/rohan/Downloads/jakstatcourier/ios/Pods/Target Support
    Files/location/location-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/UIKit.fra
    mework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly
    marked deprecated here
    @interface UIAlertView : UIView
               ^
    2 warnings generated.
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.5/ios/Classes/
    Extensions/CLPlacemarkExtensions.m:22:18: warning: 'addressDictionary' is
    deprecated: first deprecated in iOS 11.0 - Use @properties
    [-Wdeprecated-declarations]
            if (self.addressDictionary != nil) {
                     ^
    In module 'CoreLocation' imported from
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.5/ios/Classes/
    Extensions/CLPlacemarkExtensions.h:10:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/CoreLocat
    ion.framework/Headers/CLPlacemark.h:73:63: note: 'addressDictionary' has
    been explicitly marked deprecated here
    @property (nonatomic, readonly, copy, nullable) NSDictionary
    *addressDictionary API_DEPRECATED("Use @properties", macos(10.8, 10.13),
    ios(5.0, 11.0), watchos(1.0, 4.0));
                                                                  ^
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.5/ios/Classes/
    Extensions/CLPlacemarkExtensions.m:23:29: warning: 'addressDictionary' is
    deprecated: first deprecated in iOS 11.0 - Use @properties
    [-Wdeprecated-declarations]
                street = [[self addressDictionary] objectForKey:(NSString
                *)kABPersonAddressStreetKey];
                                ^
    In module 'CoreLocation' imported from
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.5/ios/Classes/
    Extensions/CLPlacemarkExtensions.h:10:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/CoreLocat
    ion.framework/Headers/CLPlacemark.h:73:63: note: property
    'addressDictionary' is declared deprecated here
    @property (nonatomic, readonly, copy, nullable) NSDictionary
    *addressDictionary API_DEPRECATED("Use @properties", macos(10.8, 10.13),
    ios(5.0, 11.0), watchos(1.0, 4.0));
                                                                  ^
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/CoreLocat
    ion.framework/Headers/CLPlacemark.h:73:63: note: 'addressDictionary' has
    been explicitly marked deprecated here
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.5/ios/Classes/
    Extensions/CLPlacemarkExtensions.m:23:73: warning:
    'kABPersonAddressStreetKey' is deprecated: first deprecated in iOS 9.0 - use
    CNPostalAddress.street [-Wdeprecated-declarations]
                street = [[self addressDictionary] objectForKey:(NSString
                *)kABPersonAddressStreetKey];
                                                                      ^
    In module 'AddressBook' imported from
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.5/ios/Classes/
    Extensions/CLPlacemarkExtensions.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/AddressBo
    ok.framework/Headers/ABPerson.h:113:29: note: 'kABPersonAddressStreetKey'
    has been explicitly marked deprecated here
    AB_EXTERN const CFStringRef kABPersonAddressStreetKey AB_DEPRECATED("use
    CNPostalAddress.street");
                                ^
    3 warnings generated.
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.5/ios/Classes/
    Extensions/CLPlacemarkExtensions.m:22:18: warning: 'addressDictionary' is
    deprecated: first deprecated in iOS 11.0 - Use @properties
    [-Wdeprecated-declarations]
            if (self.addressDictionary != nil) {
                     ^
    In module 'CoreLocation' imported from
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.5/ios/Classes/
    Extensions/CLPlacemarkExtensions.h:10:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/CoreLocat
    ion.framework/Headers/CLPlacemark.h:73:63: note: 'addressDictionary' has
    been explicitly marked deprecated here
    @property (nonatomic, readonly, copy, nullable) NSDictionary
    *addressDictionary API_DEPRECATED("Use @properties", macos(10.8, 10.13),
    ios(5.0, 11.0), watchos(1.0, 4.0));
                                                                  ^
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.5/ios/Classes/
    Extensions/CLPlacemarkExtensions.m:23:29: warning: 'addressDictionary' is
    deprecated: first deprecated in iOS 11.0 - Use @properties
    [-Wdeprecated-declarations]
                street = [[self addressDictionary] objectForKey:(NSString
                *)kABPersonAddressStreetKey];
                                ^
    In module 'CoreLocation' imported from
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.5/ios/Classes/
    Extensions/CLPlacemarkExtensions.h:10:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/CoreLocat
    ion.framework/Headers/CLPlacemark.h:73:63: note: property
    'addressDictionary' is declared deprecated here
    @property (nonatomic, readonly, copy, nullable) NSDictionary
    *addressDictionary API_DEPRECATED("Use @properties", macos(10.8, 10.13),
    ios(5.0, 11.0), watchos(1.0, 4.0));
                                                                  ^
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/CoreLocat
    ion.framework/Headers/CLPlacemark.h:73:63: note: 'addressDictionary' has
    been explicitly marked deprecated here
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.5/ios/Classes/
    Extensions/CLPlacemarkExtensions.m:23:73: warning:
    'kABPersonAddressStreetKey' is deprecated: first deprecated in iOS 9.0 - use
    CNPostalAddress.street [-Wdeprecated-declarations]
                street = [[self addressDictionary] objectForKey:(NSString
                *)kABPersonAddressStreetKey];
                                                                      ^
    In module 'AddressBook' imported from
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.5/ios/Classes/
    Extensions/CLPlacemarkExtensions.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/AddressBo
    ok.framework/Headers/ABPerson.h:113:29: note: 'kABPersonAddressStreetKey'
    has been explicitly marked deprecated here
    AB_EXTERN const CFStringRef kABPersonAddressStreetKey AB_DEPRECATED("use
    CNPostalAddress.street");
                                ^
    3 warnings generated.
    1 warning generated.
    1 warning generated.
    ../../.pub-cache/hosted/pub.dartlang.org/file-6.1.2/lib/src/interface/file.d
    art:15:16: Error: The method 'File.create' has fewer named arguments than
    those of overridden method 'File.create'.
      Future<File> create({bool recursive = false});
                   ^
    org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:232:16: Context:
    This is the overridden method ('create').
      Future<File> create({bool recursive = false, bool exclusive = false});
                   ^
    ../../.pub-cache/hosted/pub.dartlang.org/file-6.1.2/lib/src/interface/file.d
    art:15:16: Error: The method 'File.create' doesn't have the named parameter
    'exclusive' of overridden method 'File.create'.
      Future<File> create({bool recursive = false});
                   ^
    org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:232:16: Context:
    This is the overridden method ('create').
      Future<File> create({bool recursive = false, bool exclusive = false});
                   ^
    ../../.pub-cache/hosted/pub.dartlang.org/file-6.1.2/lib/src/forwarding/forwa
    rding_file.dart:22:8: Error: The method 'ForwardingFile.createSync' has
    fewer named arguments than those of overridden method 'File.createSync'.
      void createSync({bool recursive = false}) =>
           ^
    org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:248:8: Context:
    This is the overridden method ('createSync').
      void createSync({bool recursive = false, bool exclusive = false});
           ^
    ../../.pub-cache/hosted/pub.dartlang.org/file-6.1.2/lib/src/forwarding/forwa
    rding_file.dart:22:8: Error: The method 'ForwardingFile.createSync' doesn't
    have the named parameter 'exclusive' of overridden method 'File.createSync'.
      void createSync({bool recursive = false}) =>
           ^
    org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:248:8: Context:
    This is the overridden method ('createSync').
      void createSync({bool recursive = false, bool exclusive = false});
           ^
    Failed to package /Users/rohan/Downloads/jakstatcourier.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    warning: Capabilities for Signing & Capabilities may not function correctly
    because its entitlements use a placeholder team ID. To resolve this, select
    a development team in the Runner editor. (in target 'Runner' from project
    'Runner')
    /Users/rohan/Downloads/jakstatcourier/ios/Pods/Pods.xcodeproj: warning: The
    iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0,
    but the range of supported deployment target versions is 9.0 to 15.2.99. (in
    target 'leveldb-library' from project 'Pods')

    Result bundle written to path:
    	/var/folders/dt/ymx6cbj16xq_flrs8l2xzc9r0000gn/T/flutter_tools.rzO49o/flutt
    	er_ios_build_temp_dirHHxj9c/temporary_xcresult_bundle

Could not build the application for the simulator.
Error launching application on iPhone 13.
rohan@Rohans-Air jakstatcourier %

**Comment by JeroenWeener** [comment]
Hi @im-pch, thank you for filing a bug report!

Apologies for the late reply. I was wondering if you are still experiencing this issue on the latest version (2.1.0) of the geocoding plugin? I just tested the example app on an iOS 14 Pro simulator and did not encounter the error.
