### ISSUE TITLE
[iOS]PLATFORMEXCEPTION: Could not find any result for the supplied address or coordinates

### ISSUE THREAD

**Issue by KeithBacalso** [Baseflow/flutter-geocoding#112]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/49628565/196618027-5672bb96-1317-469a-9d40-129bf9846206.png)

works well on Android, but gives error in iOS.

**Comment by pinebluemeta** [comment]
Yes, I have same issue in iOS, works well on Android.

**Comment by irhas03** [comment]
I have the same issue for iOS, the places is returning empty string for couple index.

**Comment by jeeldev9** [comment]
give me solution for this error

**Comment by mvanbeusekom** [comment]
Hi @KeithBacalso, @pinebluemeta, @irhasalh and @jeeldev9,

This is a common issue and working as intended. The Geocoding plugin (as clearly mentioned in the [README](https://pub.dev/packages/geocoding)) makes use of the services provided by the platform. 

This means that on Android, Google Maps is used as backing service to do the translation, while on iOS, Apple Maps are being used. In general Google's services are more detailed and it is very well possible Apple cannot resolve an address where Google can resulting in the different behavior. 

If you'd like a reliable solution that works the same independent on the platform, I'd suggest a payed solution. There are several options available:

- Google Maps Plus API: https://developers.google.com/maps/documentation/geocoding/overview
- HERE SDK: https://developer.here.com/documentation/flutter-sdk-explore/4.3.0.0/dev_guide/index.html
- MapBox: https://pub.dev/packages/mapbox_gl
