### ISSUE TITLE
Throttle for max request limit.

### ISSUE THREAD

**Issue by anilenepal** [Baseflow/flutter-geocoding#117]
I am using the https://pub.dev/packages/geocoding geocoding package. I have a list of coordinates but it says throttle for max requests. How can i prevent the limit reach error. I like this package but i can't.

**Comment by Iron-Mike-Tyson** [comment]
The Apple documentation states that you should only send one request per minute. So I used this limit for both platforms. You can use a Timer or you work with timestamps. It depends on your case. I am using it in an applicationloop which starts, stops, restarts etc. So in my case I used the timestamp option.

Example:

var lastTimestamp = 0;
static const durationInterval = 60000; // in ms

some Loop {
  .....
   // check if adress is older than 60 seconds
   if (getTimeDifference(lastTimestamp, DateTime.now().millisecondsSinceEpoch)) {
      getAddress(lastPosition);
    }
 ......
}

 bool getTimeDifference(int oldTime, int newTime) {
    if (newTime - oldTime > durationInterval) {
      lastTimestamp = newTime;
      return true;
    }
    return false;
  }

Future<void> getAddress(GPSLocation? position) async {
    if (position != null) {
      try {
        List<Placemark> placemarks = await placemarkFromCoordinates(position.lat, position.lon);
        Placemark place = placemarks[0];
        setAddress(place.country, place.locality, place.postalCode, place.street);
......


But if you need the List instant converted, you should consider making an API-key and talk to the API directly. Check pricing before!

**Comment by JeroenWeener** [comment]
Hi @anilenepal! Thank you for reaching out with the issue you are experiencing.

As mentioned by @Iron-Mike-Tyson, geocoding functionality is rate-limited for both Android and iOS.

If you need to resolve many locations at once, you cannot make use of the free iOS and Android geocoding functionality. You should instead rely on a different API that is likely subject to service fees.
