### ISSUE TITLE
Flutter Geocoding iOS locationFromAddress not working in iOS.

### ISSUE THREAD

**Issue by adiShinwari** [Baseflow/flutter-geocoding#121]
## 🐛 Bug Report

locationFromAddress is not working in iOS. it is always returning an empty list. while the same code is working in android with the same address.
### Expected behavior
locationFromAddress should return a list of locations when you pass the address to the method.
### Configuration

**Version:** latest

**Platform:** 
- [ ] :iphone: iOS

**Comment by paulppn** [comment]
The example app seems to work fine, can you maybe elaborate/give us some more information about what data you are trying?
