### ISSUE TITLE
when providing coordinates it don't give proper places 

### ISSUE THREAD

**Issue by suhail600** [Baseflow/flutter-geocoding#122]
when providing coordinates it don't give proper places , it shows some list of places even if i provide exact coordinates from google it doesn't provide correct location name or address, how to solve this  or is this an error?

**Comment by Iron-Mike-Tyson** [comment]
Just try the first element:

List<Placemark> placemarks = await placemarkFromCoordinates(latitude, longitude);
Placemark place = placemarks[0];

var country = place.country;
var city = place.locality;
var postalCode = place.postalCode;
var streetAndNumber = place.street;

**Comment by mvanbeusekom** [comment]
Hi @suhail600,

Thank you for submitting this issue. The Geocoding plugin utilises the free geocoding frameworks provided by the platform. As these services are "free" it means (as mentioned in the [README](https://pub.dev/packages/geocoding)) there are some restrictions and we cannot provide any guarantees on the results provided by these SDKs.

If you feel this is unfair or incorrect, the best advise I can provide is to file a bug for the appropriate platform:
- To file an issue with Apple: https://developer.apple.com/bug-reporting/
- To file an issue with Google: https://source.android.com/docs/setup/contribute/report-bugs
