### ISSUE TITLE
Flutter Web Support

### ISSUE THREAD

**Issue by Sun3** [Baseflow/flutter-geocoding#125]
## 🚀 Feature Requests

Any updates if the Flutter Web support will be added to the geocoding? Or any workarounds?

### Contextualize the feature
Since I am using geolocator and it supports the Web, I would be great if geocoding will also support the Web.

### Describe the feature
Ability to get geolocation street address by working together with the geocoding package.

### Platforms affected (mark all that apply)
- [x] :web: Web
- [ ] :iphone: iOS
- [ ] :robot: Android

Thank you.

**Comment by Sun3** [comment]
Any suggestions around this issue for the Web?

Thank you.

**Comment by malkhan-singh-gaur** [comment]
Yes. I am also having this issue. Please add web support for geocoding.
