### ISSUE TITLE
Does this package use Google Places Geolocation API

### ISSUE THREAD

**Issue by ReaganRealones** [Baseflow/flutter-geocoding#13]
## Does this package use Google Places Geolocation API

Okay, my question is, on the introduction section of this package. There's the following note 

> This plugin uses the **free Geocoding** services provided by the iOS and Android platforms. This means that there are restrictions to their use. More information can be found in the Apple documentation for iOS and the Google documentation for Android.

Then Visiting [Google Maps Billing i.e places tab](https://cloud.google.com/maps-platform/pricing) , the current charge for geocoding as of now is $5 per 1000 requests.

So I guess my main question is, if this package uses a free API, why does Google Maps make us pay if we are to use their service instead. Is the Google Maps geocoding service i.e place cordinates and names just updated more frequently or something? My application heavily relies on GeoCoding by giving address to location co-ordinates. So what do you advise? Should I use the free Geocoding services throught this package or go with the paid Google maps geocoding API, is it worth it, or do they do 100% the same thing? 

Thank you...

**Comment by mvanbeusekom** [comment]
No this package uses the default geocoding services provided on the platform you run your App on. This means:

1. On Android we use the [Geocoder](https://developer.android.com/reference/android/location/Geocoder) API which relies on a backend service installed with Google Play Services;
2. On iOS devices we use  the [CLGeocoder](https://developer.apple.com/documentation/corelocation/clgeocoder) API which relies on a free version of the Apple Maps SDK.
