### ISSUE TITLE
Can't get postalCode

### ISSUE THREAD

**Issue by PhaHoeun** [Baseflow/flutter-geocoding#139]
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
*** When I use geocoding, I can't get postalCode for my country Cambodia. Other country is okay. Please help check and solve it. Thanks!

**Comment by paulppn** [comment]
Unfortunately all we do is expose the Android Geocoder and the iOS CLGeocoder class, if there is anything missing you will have to address it there.
