### ISSUE TITLE
PlatformException (PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates (latitude: 30.867672, longitude: 122.209517)., null, null)) for Android version 7.1.2

### ISSUE THREAD

**Issue by Deepak96321** [Baseflow/flutter-geocoding#141]
List<Placemark> placemarks = await placemarkFromCoordinates(
     26.8380, 80.8765,localeIdentifier: "en");
          print("placemarks:: $placemarks");

thisi is my code I am getting error for real device redmi 4 ,android version 7.1.2

**Comment by yazanalkamsheh** [comment]
I have also the same issue >> this problem show in console 

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates (latitude: ٤٠٫٧١٢٧٢٨, longitude: -٧٤٫٠٠٦٠١٥)., null, null)
E/flutter (25832): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (25832): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter (25832): <asynchronous suspension>
E/flutter (25832): #2      GeocodingAndroid.placemarkFromCoordinates (package:geocoding_android/geocoding_android.dart:56:9)
E/flutter (25832): <asynchronous suspension>

I'm use my device Samsung A52s

**Comment by maulikchak** [comment]
same issue

**Comment by mvanbeusekom** [comment]
Hi,

As mentioned in the [README](https://pub.dev/packages/geocoding) attached to this plugin:

> This plugin uses the free Geocoding services provided by the iOS and Android platforms. This means that there are restrictions to their use. More information can be found in the [Apple documentation for iOS](https://developer.apple.com/documentation/corelocation/clgeocoder) and the [Google documentation for Android](https://developer.android.com/reference/android/location/Geocoder). When a PlatformException(IO_ERROR, ...) gets thrown, most of the times it means that the rate limit has been reached.

There is nothing we can do about it. There are paid alternatives available which remove the rate limit constraints.
