### ISSUE TITLE
Deprecated reverse geocodage on iOS 16

### ISSUE THREAD

**Issue by kevinderome** [Baseflow/flutter-geocoding#142]
## 🐛 Bug Report
I am able to test my code but when I archive it XCode tells me that your package uses deprecated methods.
It also points to the geocoderr package.
### Expected behavior
it's impossible to archive my code with XCode.
### Reproduction steps
I use this code:
```
List<Placemark> placemarks =
             await placemarkFromCoordinates(position.latitude, position.longitude);
```
### Configuration
geocoding 2.1.0
Flutter 3.7.9 ? channel stable ? https://github.com/flutter/flutter.git
Framework ? revision 62bd79521d (7 days ago) ? 2023-03-30 10:59:36 -0700
Engine ? revision ec975089ac
Tools ? Dart 2.19.6 ? DevTools 2.20.1
XCode 14
**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android

**Comment by TimHoogstrate** [comment]
Is resolved by: [174](https://github.com/Baseflow/flutter-geocoding/pull/174)
