### ISSUE TITLE
PlatformException(IO_ERROR, Error Domain=kCLErrorDomain Code=2 "(null)", null, null)

### ISSUE THREAD

**Issue by akshaynjarangal** [Baseflow/flutter-geocoding#143]
## 🐛 Bug Report
@BeMacized  @martijn00  @mvanbeusekom 

### Expected behavior

PlatformException(IO_ERROR, Error Domain=kCLErrorDomain Code=2 "(null)", null, null)

### Reproduction steps

```dart
static Future<Placemark> getPlaceName(
      {required double lat, required double long}) async {
    try {
      final place = await placemarkFromCoordinates(lat, long);
      log(place[0].toJson().toString());
      return place[0];
    } catch (e) {
      log(e.toString());
      //PlatformException(IO_ERROR, Error Domain=kCLErrorDomain Code=2 "(null)", null, null)
    }
  }
```

### Configuration

**Version:** 2.1.0 (geocoding)

Flutter 3.7.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ad6cd72c0 (5 weeks ago) • 2023-03-08 09:41:59 -0800
Engine • revision 1837b5be5f
Tools • Dart 2.19.4 • DevTools 2.20.1

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @akshaynjarangal,

As mentioned in the [README](https://pub.dev/packages/geocoding) attached to this plugin:

> This plugin uses the free Geocoding services provided by the iOS and Android platforms. This means that there are restrictions to their use. More information can be found in the [Apple documentation for iOS](https://developer.apple.com/documentation/corelocation/clgeocoder) and the [Google documentation for Android](https://developer.android.com/reference/android/location/Geocoder). When a PlatformException(IO_ERROR, ...) gets thrown, most of the times it means that the rate limit has been reached.

There is nothing we can do about it. There are paid alternatives available which remove the rate limit constraints.
