### ISSUE TITLE
The places returned are incorrect

### ISSUE THREAD

**Issue by Jeanetted3v** [Baseflow/flutter-geocoding#144]
## 🐛 Bug Report

placemarks[0].locality doesn't return city names. 
For example, i keyed in coordinates of Hong Kong, it returned 'Mong Kok', which is a district in 'Hong Kong'. 
It returned 'Hong Kong' when I use placemarks[0].administrativeArea. 
For example, I keyed in coordinates of Singapore, it just returned nothing for both. 
I'm using iOS stimulator

**Comment by TimHoogstrate** [comment]
Dear @Jeanetted3v, can you help resolving this issue by adding the output of `flutter doctor -v` to the to this issue? Furthermore, we would like to have detailed steps to reproduce. It would help a lot if you can supply the coordinates that you are using?
