### ISSUE TITLE
Geocoding not working on Pixel 6 GrapheneOS with installed Google services

### ISSUE THREAD

**Issue by ciomeczek** [Baseflow/flutter-geocoding#146]
I am currently using the Geocoding Flutter package (version 2.1.0) in my application, and I have encountered an issue with the package on the Pixel 6 device running GrapheneOS.

Despite having installed Google services on the device, the Geocoding package does not seem to be functioning correctly. Specifically, it is unable to geocode any addresses or locations.

I have tested the same code on other Android devices with Google services installed and it works perfectly fine. Additionally, I have tested other location-based functionalities on my Pixel 6 device with GrapheneOS, and they seem to be working fine.

Could you please investigate this issue and provide a solution or workaround? Let me know if you need any additional information from my end.

Steps to reproduce:

1. Install Geocoding Flutter package version 2.1.0 on an app
2. Use the package to geocode an address or location on a Pixel 6 device running GrapheneOS with Google services installed.
3. Observe that geocoding does not work.

Expected result:
The package should be able to geocode addresses or locations on all Android devices with Google services installed, including the Pixel 6 device running GrapheneOS.

Actual result:
Geocoding is not functioning on the Pixel 6 device running GrapheneOS with Google services installed. A platform exception is being thrown in the app.

Device information:

- Device: Pixel 6
- Operating system: GrapheneOS (version TQ2A.230405.003.E1.2023041100)
- Google services version: (version 23.13.12)

Thank you for your help in resolving this issue. Let me know if you need any additional information from my end.

**Comment by JeroenWeener** [comment]
Hi @ciomeczek, thank you for reaching out to us!

Let me preface this by saying I am not too familiar with GrapheneOS.

What I found online is that GrapheneOS aims to be an Android flavor that not dependent on Google or their services, in an attempt to increase privacy and security: https://grapheneos.org/. This means that by default, Google Play Services are not installed. Users can install it manually, however. As the `geocoding` plugin makes use of the Play Services, users of GrapheneOS need to have these installed.

Did you follow their instructions?
https://grapheneos.org/faq#google-services
https://grapheneos.org/usage#sandboxed-google-play

You mention receiving a `PlatformException`. Can you post the exception and stack trace here? This will help us identify the root cause of the issue you are experiencing.

**Comment by ciomeczek** [comment]
Hi @JeroenWeener, I really appreciate your response

All necessary Google services are indeed installed on my Pixel 6 device running GrapheneOS. I have also tested the geocoding functionality using another app on the same device, and it works without any issues. Therefore, it seems that the problem is specific to the Geocoding Flutter package rather than the device or Google services.

The stacktrace I receive when attempting to geocode is as follows:

```
[+1575 ms] D/ProfileInstaller( 4483): Installing profile for app.drinkify
[+1269 ms] E/flutter ( 4483): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(NOT_FOUND, No address information found for supplied coordinates (latitude:
50,495008, longitude: 30,514120)., null, null)
[        ] E/flutter ( 4483): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
[        ] E/flutter ( 4483): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
[        ] E/flutter ( 4483): <asynchronous suspension>
[        ] E/flutter ( 4483): #2      GeocodingAndroid.placemarkFromCoordinates (package:geocoding_android/geocoding_android.dart:56:9)
[        ] E/flutter ( 4483): <asynchronous suspension>
[        ] E/flutter ( 4483): #3      _CreatePartyRouteState.build.<anonymous closure> (package:drinkify/routes/create_party_page.dart:221:25)
[        ] E/flutter ( 4483): <asynchronous suspension>
[        ] E/flutter ( 4483): 
[+2334 ms] I/flutter ( 4483): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
[        ] I/flutter ( 4483): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
[        ] I/flutter ( 4483): <asynchronous suspension>
[        ] I/flutter ( 4483): #2      GeocodingAndroid.placemarkFromCoordinates (package:geocoding_android/geocoding_android.dart:56:9)
[        ] I/flutter ( 4483): <asynchronous suspension>
[        ] I/flutter ( 4483): #3      _CreatePartyRouteS
```

Also this is ``drinkify/routes/create_party_page.dart:221``

```
loc = await placemarkFromCoordinates(
  posData.latitude!,
  posData.longitude!,
);
```

This exception is thrown when trying to geocode a specific set of coordinates. However, as mentioned earlier, the same coordinates work fine with another app on the same device.

I would like to also emphasize that I have tested the same code and addresses on other Android devices (without GrapheneOS) with Google services installed, and the geocoding works perfectly fine.

I have also verified that the coordinates and addresses I'm trying to geocode are valid and have been successfully geocoded using other geocoding services.

**Comment by JeroenWeener** [comment]
Hi @ciomeczek, thank you for getting back to me with additional information.

Unfortunately, GrapheneOS does not come with a geocoding solution. These solutions typically connect to a third-party server, which is something privacy-aware OSes try to avoid.

There was an issue on the GrapheneOS repository where a member replied, saying that this is something they are considering, but it is not a feature currently: https://github.com/GrapheneOS/os-issue-tracker/issues/2070#issuecomment-1492868238.

You can find the issue that tracks the geocoding implementation in GrapheneOS here: https://github.com/GrapheneOS/os-issue-tracker/issues/23.

I wish I could help out, but this is out of our hands.
