### ISSUE TITLE
Some doubts abouts this geocoding plugin

### ISSUE THREAD

**Issue by BhaskarTrigsy** [Baseflow/flutter-geocoding#147]
## 💬 Questions and Help

We are using the gecoder package for the flutter .But we have some questions
1.Is it free for commercial usage as well?
2.Does this use google geocoding api?
3.If yes, how is this free when google charges per request?
4.If No, how does this get location details and how is ensure that it remains updated with latest data?

**Comment by TimHoogstrate** [comment]
Hi thanks for your feedback,

1) Please check the attached MIT License
2-4) Feel free to look into the code for any detailed information.

I'm closing this issue, feel free to reopen it when you have any additional questions.
