### ISSUE TITLE
Error: MissingPluginException(No implementation found for method locationFromAddress on channel flutter.baseflow.com/geocoding)

### ISSUE THREAD

**Issue by davitkhalatyan** [Baseflow/flutter-geocoding#150]
I am getting this MissingPluginException error and it is caused by my locationFromAddress call and it prevents the navigator to function.
The code worked properly before I added locationFromAddress. What can this error mean and how do I fix this? 

here is my code
`import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:geolocator/geolocator.dart';
import 'package:geocoding/geocoding.dart';

@override
  void didChangeDependencies() {
    super.didChangeDependencies();
    SchedulerBinding.instance.addPostFrameCallback((_) async {
      userPosition = await getUserPosition();
      locs = await GeocodingPlatform.instance.locationFromAddress('my address');
      loc = locs.first;
      if (context.mounted) {
        Navigator.pushReplacementNamed(context, 'map', arguments: {
          'userPosition': userPosition,
          'loc': loc,
        });
      }
    });
  }

  Position? userPosition;
  Location? loc;
  List<Location> locs = [];

  @override
  Widget build(BuildContext context) {...}`

**Comment by petitsuix** [comment]
Are you running it on a navigator ?
