### ISSUE TITLE
How do I test this?

### ISSUE THREAD

**Issue by oakstair** [Baseflow/flutter-geocoding#157]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geocoding/blob/main/geocoding/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [ ] iOS

### Your question

I fail to write a test that uses this package.

```dart
    // FIXME. Does not work
    DartPluginRegistrant.ensureInitialized();
    TestWidgetsFlutterBinding.ensureInitialized();

    GetIt.I.registerSingleton<GeoService>(GeoServiceImpl());
    final GeoService geo = GetIt.I<GeoService>();

    test('GeoCoder.getPosition', () async {
      const LatLng rodebyCentrumPos = LatLng(56.2610053, 15.6166791);
      final LatLng? pos = await geo.getPosition('Rödeby Centrumhus Movägen, 370 30 Rödeby');
      expect(geo.distance(rodebyCentrumPos, pos!), closeTo(0.0, 100.0));

      final LatLng? myPosition = await geo.getPosition('Teknologgatan 3, 11360 Stockholm');
      final String? myAddress = await geo.getAddress(myPosition!);
      expect(myAddress, 'Teknologgatan 3, 113 60 Stockholm, Sweden');
    });
```

This gives me an exception in my service that is calling locationFormAdress

`MissingPluginException(No implementation found for method locationFromAddress on channel flutter.baseflow.com/geocoding)`

### Version

2.1.0

**Comment by mvanbeusekom** [comment]
Hi @oakstair,

Thanks for submitting this issue. 

Let me first start of with explaining why the test fails. The Geocoding plugin relies on platform specific implementation that is only available when running on a real or simulated device. If you are running these tests in a Dart test environment, Flutter won't load any platform specific implementation resulting in the `MissingPluginException`. 

Theoretically you could write your own mock method channels, mocking the platform specific implementation however this means you writing tests we have already written. Also it is considered a bad practise to mock types that you don't own, this is discussed in more detail by the paper "[Mock roles, not Objects](http://jmock.org/oopsla2004.pdf)" by Steve Freeman and Nat Pryce (specifically chapter 4.1). In this case it would be better to write an adapter and mock your own adapter. The article "[Testing plugins](https://docs.flutter.dev/testing/testing-plugins)" on the Flutter documentation site explains how to go about mocking method channels (which I think in this case you really shouldn't be doing).

If you want to test the integration, you probably want to write an integration test that executes on a real or emulated device. More information on how to set this up can be found in the articles "[Integration testing](https://docs.flutter.dev/testing/integration-tests)" and "[Recipe: An introduction to integration testing](https://docs.flutter.dev/cookbook/testing/integration/introduction)".

Hopefully this will provide you with the information you need to continue.
