### ISSUE TITLE
MissingPluginException 

### ISSUE THREAD

**Issue by ZaidSameer** [Baseflow/flutter-geocoding#16]
## 💬 I am getting this error:
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method placemarkFromCoordinates on channel flutter.baseflow.com/geocoding))

**Here are my function**
`  Future<String> getCityName(double lat, double lon) async {
    List<Placemark> placemark = await placemarkFromCoordinates(lat, lon);
    print('City Name ${placemark[0].locality}');
    return placemark[0].locality;
  }
}`

I am using this version: `geocoding: ^1.0.4`

**Comment by ZaidSameer** [comment]
It was a Hot reload issue.

**Comment by vbabaria** [comment]
tried rerunning entire app but i still get same error. any suggestion would greatly appreciated - thanks

Flutter project doesn't pulls latest version of geocoding library (it refers to ^1.0.5) because of dependency conflict.
