### ISSUE TITLE
[Bug]: GeocodingIOS.placemarkFromCoordinates (geocoding_ios.dart:56) - Fatal Exception:  PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates 

### ISSUE THREAD

**Issue by giorgio79** [Baseflow/flutter-geocoding#160]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geocoding/blob/main/geocoding/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS

### Steps to reproduce

Occasional network error when getting placemark 

### Expected results

no error, or at least not fatal

### Actual results

fatal error

### Code sample

[Bug]: GeocodingIOS.placemarkFromCoordinates (geocoding_ios.dart:56) - Fatal Exception:  PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates 

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

latest

### Flutter Doctor output

flutter doctor reports no issues

**Comment by JeroenWeener** [comment]
Hi @giorgio79, thank you for filing your bug report!

Could it be that you are hitting the rate limit of the Apple geocoding service?

From the README:
---
Important:

This plugin uses the free Geocoding services provided by the iOS and Android platforms. This means that there are restrictions to their use. More information can be found in the [Apple documentation for iOS](https://developer.apple.com/documentation/corelocation/clgeocoder) and the [Google documentation for Android](https://developer.android.com/reference/android/location/Geocoder). When a PlatformException(IO_ERROR, ...) gets thrown, most of the times it means that the rate limit has been reached.

**Comment by giorgio79** [comment]
Thx Jeroen. What is interesting is that many phones are Android that report the error for GeocodingIOS. Is the library handling the platform separation correctly?
![image](https://github.com/Baseflow/flutter-geocoding/assets/283347/8858844a-f77e-4ee8-a92c-1641e6b587a1)

**Comment by giorgio79** [comment]
Raising this ios calls for android phones as a separate issue :)

**Comment by JeroenWeener** [comment]
Link to new issue: https://github.com/Baseflow/flutter-geocoding/issues/162

**Comment by keyurgit45** [comment]
@JeroenWeener I tried to find the rate limit for the geocoding package but couldn't find it, could you please help me with that?
