### ISSUE TITLE
Gradle file not updated

### ISSUE THREAD

**Issue by TiffApps** [Baseflow/flutter-geocoding#163]
Here is my build.gradle for this package (v2.1.0) :

```gradle
group 'com.baseflow.geocoding'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 33

    defaultConfig {
        minSdkVersion 16
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.4.0'
}
```

As you can see, it hasn't taken in account the updates I see on this repo, for example the Gradle version or the [new namespace compatibility](https://github.com/Baseflow/flutter-geocoding/blob/d13a6d602582dd90aca97203b1f420e1cb0ed0ee/geocoding_android/android/build.gradle#L25C1-L29C1).

I have no idea why it didn't update, but yeah I ran a `flutter pub cache clean` and `flutter clean`, made sure it was updated to 2.1.0, but I still get this issue.

**Comment by mb1shka** [comment]
<img width="996" alt="Screenshot 2023-07-21 at 01 31 54" src="https://github.com/Baseflow/flutter-geocoding/assets/80235393/5c3ba430-37dd-4c03-bf60-e2d5b3155dd5">
Same issue.
I added this to manifest and everything worked.
I don't want to fork the library and hope someone of developers will fix this bug soon.

**Comment by TiffApps** [comment]
Closing this as it solved itself apparently.
