### ISSUE TITLE
Implement for flutter web

### ISSUE THREAD

**Issue by asarkar101** [Baseflow/flutter-geocoding#164]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).

### Please select affected platform(s)

- [ ] Android
- [ ] iOS

### Use case

Implement for flutter web

### Proposal

Implement for flutter web

**Comment by JeroenWeener** [comment]
Hi @asarkar101, thank you for filing a feature request.

We are currently not considering adding web support for the geocoding plugin.

For Android and iOS, it makes sense to give Flutter developers access to the native APIs used for geocoding. These are [Geocoder](https://developer.android.com/reference/android/location/Geocoder) for Android and [CLGeocoder](https://developer.apple.com/documentation/corelocation/clgeocoder?language=objc) for iOS.
For web, however, things are a bit different, as there is not one logical choice for a geocoding endpoint. There are many suppliers and we trust the community or those suppliers to create a geocoding plugin for that specific service. An example of such plugin is [geocode.xyz](https://pub.dev/packages/geocode). This plugin supports web and could fit your needs.
