### ISSUE TITLE
Execution failed for task ':geocoding_android:processDebugManifest'.

### ISSUE THREAD

**Issue by sjyeoh1996** [Baseflow/flutter-geocoding#165]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geocoding/blob/main/geocoding/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS

### Your question

![image](https://github.com/Baseflow/flutter-geocoding/assets/121526603/d812e70a-8242-45f3-9284-b08a0b6ac7f8)
im getting this issue when running my flutter project

### Version

geocoding: ^2.1.0

**Comment by sjyeoh1996** [comment]
and i check the androidManifest.xml file from given path, it shows like this only
![image](https://github.com/Baseflow/flutter-geocoding/assets/121526603/e3d8e014-1163-4b69-8d86-0137818024d1)

**Comment by mohammad-abuhummos** [comment]
have same issue any fix?

**Comment by sjyeoh1996** [comment]
i just update my kotlin version in android/grandle
ext.kotlin_version = '1.9.0'

and set the classpath version to
classpath 'com.android.tools.build:gradle:7.2.0'

and then go to grandle/wrapper/grandle-wrapper.properties
set the distribution to 
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip

after that at terminal cd into android then run 
gradlew clean build

after all those above then it fixed my problem
