### ISSUE TITLE
flutter pub failed

### ISSUE THREAD

**Issue by justsaagar** [Baseflow/flutter-geocoding#168]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).

### Please select affected platform(s)

- [X] Android
- [X] iOS

### Old behavior

I am able to do pub get but now not able to do so.

### Current behavior

Currently not able to do pub get getting following exception: 

`Because no versions of geocoding_ios match 2.1.0 and no versions of geocoding_ios match >2.1.0 <3.0.0, geocoding_ios ^2.1.0 is forbidden.
So, because b2c depends on geocoding ^2.1.0 which depends on geocoding_ios ^2.1.0, version solving failed.`

### Steps to reproduce

1. flutter clean
2. flutter pub get

### Code sample

<details><summary>Code sample</summary>

```dart
  # Get live location :
  geocoding: ^2.1.0

```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

<img width="1822" alt="image" src="https://github.com/Baseflow/flutter-geocoding/assets/81945297/90939bcd-35bb-4897-ad90-a47eddde334e">

</details>

### Current version

^2.1.0

### Last version without regression

^2.1.0

**Comment by justsaagar** [comment]
@stereotype441 @pento @BeMacized @grahamsmith  any solution for this?

**Comment by JeroenWeener** [comment]
Hi @justsaagar, thank you for filing a bug report.

This is strange behavior indeed, as `geocoding_ios: 2.1.0` is available from pub.dev: https://pub.dev/packages/geocoding_ios/versions.

Are you by any chance using a different package distributor, or running some sort of middleware? Some companies that want to harness the security and integrity of their software opt for using their own package manager.

I have tried to reproduce the issue just in case.
1. `flutter create temp`
2. Update `pubspec.yaml` to include `geocoding: ^2.1.0`
3. `flutter pub get`

But I do not get an error when resolving the packages.

If you believe you are indeed fetching packages from pub.dev, could you try to follow the steps I took and confirm whether you are still encountering the issue?

**Comment by justsaagar** [comment]
No. Thanks i fixed the issue. Actually this issue is comming becuase of rmp files in **pub.cache** file of my mac.

For solution i have just delete this folder and again run **flutter pub cache repair** command and fixed.
