### ISSUE TITLE
[Bug]: Build fails with exception of missing file

### ISSUE THREAD

**Issue by milindgoel15** [Baseflow/flutter-geocoding#169]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geocoding/blob/main/geocoding/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS

### Steps to reproduce

1. add latest geocoding
2. build the android apk 
3. throws error.

### Expected results

Build compiles successfully

### Actual results

```console
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':geocoding_android:compileReleaseJavaWithJavac' (type 'JavaCompile').
  - Type 'org.gradle.api.tasks.compile.JavaCompile' property 'options.compilerArgumentProviders.$1.annotationProcessorListFile' specifies file 'D:\Programming\Flutter-projects\WeatherWiseApp\weatherwise\build\geocoding_android\intermediates\annotation_processor_list\release\annotationProcessors.json' which doesn't exist.

    Reason: An input file was expected to be present but it doesn't exist.

    Possible solutions:
      1. Make sure the file exists before the task is called.
      2. Make sure that the task which produces the file is declared as an input.     

    Please refer to https://docs.gradle.org/7.5/userguide/validation_problems.html#input_file_does_not_exist for more details about this problem.
```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

2.1.2

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
@Milind ➜ ~ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.22621.2215], locale en-IN)
    • Flutter version 3.13.2 on channel stable at D:\Programming\sdks\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (13 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Lenovo\AppData\Local\Android\Sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • ANDROID_SDK_ROOT = C:\Users\Lenovo\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33712.159
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code, 64-bit edition (version 1.81.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.66.0

[✓] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.22621.2215]

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by milindgoel15** [comment]
Sure,

For android/app/build.gradle:
https://katb.in/Appgradle

For android/build.gradle:
https://katb.in/Rootgradle

**Comment by mvanbeusekom** [comment]
@milindgoel15, I am looking into this issue but am not yet able to reproduce it. 

Searching the internet I found an article where people suggested to delete the `android/.gradle` folder and try to recompile it using `flutter build apk`.

What maybe would also help if you could run `flutter build apk --verbose` and share the output. This would give us a lot more details and hopefully helps to resolve the issue.

**Comment by milindgoel15** [comment]
https://katb.in/aliwexiqiki
logs while building apk using verbose flag

> Searching the internet I found an article where people suggested to delete the `android/.gradle` folder and try to recompile it using `flutter build apk`.

And you were right, deleting the .gradle folder does work. But I don't know why it wouldn't work all of a sudden. Like when the error started appearing, I had built one apk already a few minutes before it and no change was made to any build.gradle file.

**Comment by mvanbeusekom** [comment]
Hi @milindgoel15,

Glad to hear removing the `.gradle` folder worked. To me it is also not really clear what is causing this issue, however there are several other people on the internet reporting this issue every now and then. 

I am going ahead and close this issue. Feel free to leave a comment if it pops up again and maybe we can look in to it deeper (al though it seems more a generic issue related to the Android build system).
