### ISSUE TITLE
[Question]:  I am trying to Use GeoCoding for Converting Longitude & latitude to It's corresponding Address but getting an error :  I/flutter ( 5989): Error: MissingPluginException(No implementation found for method placemarkFromCoordinates on channel flutter.baseflow.com/geocoding)

### ISSUE THREAD

**Issue by desaimann37** [Baseflow/flutter-geocoding#172]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geocoding/blob/main/geocoding/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS

### Your question

![Screenshot (35)](https://github.com/Baseflow/flutter-geocoding/assets/96511880/d5df1cba-a830-4c13-91bd-aee39f1954e8)

Code file : 

```dart
import 'package:flutter/material.dart';
import 'package:geocoding/geocoding.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: ConvertLatLngToAddress(),
    );
  }
}

class ConvertLatLngToAddress extends StatefulWidget {
  @override
  _ConvertLatLngToAddressState createState() => _ConvertLatLngToAddressState();
}

class _ConvertLatLngToAddressState extends State<ConvertLatLngToAddress> {
  double latitude = 33.6992;
  double longitude = 72.9744;
  String address = '';

  void _convertCoordinatesToAddress() async {
    try {
      List<Placemark> placemarks =
      await placemarkFromCoordinates(latitude, longitude);
      if (placemarks != null && placemarks.isNotEmpty) {
        Placemark placemark = placemarks[0];
        setState(() {
          address =
          '${placemark.street}, ${placemark.locality}, ${placemark.administrativeArea}, ${placemark.country}';
        });
      }
    } catch (e) {
      print('Error: $e');
      setState(() {
        address = 'Error converting coordinates to address';
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Convert Coordinates to Address'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Text('Latitude: $latitude'),
            Text('Longitude: $longitude'),
            ElevatedButton(
              onPressed: _convertCoordinatesToAddress,
              child: Text('Convert to Address'),
            ),
            SizedBox(height: 20.0),
            Text(
              'Address: $address',
              style: TextStyle(fontSize: 18.0),
            ),
          ],
        ),
      ),
    );
  }
}
```

### Version

  geocoding: ^2.1.0

**Comment by desaimann37** [comment]
If you found any Solution please let me know because I need to present this in College !! So ASAP...

**Comment by mvanbeusekom** [comment]
@desaimann37, I have copied the provided code in a new Flutter application and tested it on a Pixel 7a without any issues. Meaning I am unable to reproduce the problem. 

It is possible that something is wrong with the version of the geocoding plugin that are cached locally on your machine. Try running the following commands to make sure everything is up to date:

```shell
# Clean earlier build outputs and files cached during the build process.
flutter clean
# Download the latest versions of all dependencies.
flutter pub upgrade
```

If this doesn't work for you please provide the contents of the `pubspec.lock` file and the output of the `flutter doctor -v` command.

**Comment by KyawLwinSoe27** [comment]
I also got this kind of error message from geolocator on IOS.
flutter: MissingPluginException(No implementation found for method placemarkFromCoordinates on channel flutter.baseflow.com/geocoding)

Is there any soluction for this? Below is my code 

Position position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.high);
    List<Placemark> placeMarks = [];
    try{
      // Get placemarks from coordinates
      List<Placemark> placeMarks = await placemarkFromCoordinates(
          position.latitude, position.longitude);
    } catch(Exception) {
      print(Exception);
  }

**Comment by KyawLwinSoe27** [comment]
I solved this issued on IOS , I rerun flutter clean and flutter pub get and also pod update . This is no longer exception.
