### ISSUE TITLE
Please update UUID to 4.1.0, this imcompability blocks entire update of other packages in projects using this, thanks.

### ISSUE THREAD

**Issue by menezes85** [Baseflow/flutter-geocoding#173]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).

### Please select affected platform(s)

- [X] Android
- [X] iOS

### Use case

Please update UUID to 4.1.0, this imcompability blocks entire update of other packages in projects using this, thanks.

### Proposal

Please update UUID to 4.1.0, this imcompability blocks entire update of other packages in projects using this, thanks.

### Specific requirements or considerations

Please update UUID to 4.1.0, this imcompability blocks entire update of other packages in projects using this, thanks.

### Additional information or context

Please update UUID to 4.1.0, this imcompability blocks entire update of other packages in projects using this, thanks.

**Comment by mvanbeusekom** [comment]
Hi @menezes85,

Our geocoding plugin doesn't reference the UUID package. Did you accidentally create this issue in the wrong repository?
