### ISSUE TITLE
[Bug]: Error (Xcode): Framework 'geocoding' not found,Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by ChristineWasike** [Baseflow/flutter-geocoding#175]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geocoding/blob/main/geocoding/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS

### Steps to reproduce

1. Run `pod install` on Flutter project
2. This led to the issue` Error (Xcode): Framework 'geocoding' not found,Error (Xcode): Linker command failed with exit code use -v to see invocation)`
3. Then run the next three to clear cache `pod deintegrate`.
4. `pod cache clean --all`
5. `pod install`

### Expected results

I anticipated that my pods would be updated but the geocoding framework would be retained

### Actual results

Instead, the **_geocoding_** framework changed to **_geocoding_ios_** and hence, it is not recognizable on my machine throwing this error:
```
Error (Xcode): Framework 'geocoding' not found
Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 11 pro.
```

### Code sample

<details><summary>Code sample</summary>

```dart
pod install on the terminal
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

2.0.4

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.6 22G120 darwin-arm64, locale en-KE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by mvanbeusekom** [comment]
Hi @ChristineWasike,

Did you try running the following commands:

```shell
# Clean Flutter generated output
flutter clean

# Update and install all Flutter dependencies
flutter pub upgrade

# Build the iOS version of the application
flutter build ios --no-codesign
```

Please let me know if this helps.
