### ISSUE TITLE
[Question]: Limit the region on search location

### ISSUE THREAD

**Issue by KelvinLR** [Baseflow/flutter-geocoding#176]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geocoding/blob/main/geocoding/README.md).

### Please select for which platform(s) you need help

- [x] Android
- [x] iOS

### Your question

Hello, can you help me about a little question? I want to search a location on a specific region, how can I limit my search to do this?
Example: I live in Fortaleza, and I want to do an app to search locals only on my region.

### Version

2.1.1

**Comment by TimHoogstrate** [comment]
Dear @KelvinLR,

You could play around with: https://developers.google.com/maps/documentation/javascript/examples/geocoding-simple. Perhaps you can add a prefix to the search like e.g. Brazil [seached text] or Fortaleza [searched text].

Kind regards,
