### ISSUE TITLE
[Question]:  Am getting plus code instead of street name

### ISSUE THREAD

**Issue by RoxDevvv** [Baseflow/flutter-geocoding#177]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geocoding/blob/main/geocoding/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS

### Your question

am trying to get street name but am getting plus code instead ! 

### Version

2.1.1

**Comment by TimHoogstrate** [comment]
Dear @RoxDevvv,

Can you elaborate a bit on the subject? Can you inform us about the expected result and the result that you actually see?

Kind regards,
