### ISSUE TITLE
PlatformException(NOT_FOUND, No address information found for supplied coordinates (latitude: 52.216516, longitude: 6.943782)., null, null)

### ISSUE THREAD

**Issue by ibrohabib** [Baseflow/flutter-geocoding#18]
i use this code
`List<Placemark> placemarks =
          await placemarkFromCoordinates(52.2165157, 6.9437819);`

I already done all preparation based on this:
https://github.com/Baseflow/flutter-geocoding#usage

import these package:
import 'package:geocoding/geocoding.dart';
import 'package:geocoding_platform_interface/geocoding_platform_interface.dart';

add permission AndroidManifest
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

I got this error:
PlatformException(NOT_FOUND, No address information found for supplied coordinates (latitude: 52.216516, longitude: 6.943782)., null, null)

i have look at other issue the other face, and try it, but nothing work.
hot reload, restart, flutter clean, uninstall apk.

**Comment by mvanbeusekom** [comment]
Hi @ibrohabib, you will get this error when the backend services (Apple or Google depending on the platform you are using) cannot find address information for the supplied coordinates. This is something we don't have control over and is managed by Apple or Google (depending if you are running on iOS or Android).

**Comment by Shiba-Kar** [comment]
Just run on a physical device

**Comment by FarrukhSajjad** [comment]
I am running it on a physical device but still it is responding the same

**Comment by mvanbeusekom** [comment]
@FarrukhSajjad as mentioned in my previous reply, this error is thrown when the Android or iOS backend services can't find an address for the supplied coordinates. This is not something we have control over.
