### ISSUE TITLE
[Bug]: Dependency versions are old

### ISSUE THREAD

**Issue by lukehutch** [Baseflow/flutter-geocoding#183]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geocoding/blob/main/geocoding/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS

### Steps to reproduce

The latest version of `geocoding` in pub.dev is 2.1.1. This depends upon `geocoding_platform_interface` 2.0.1, which is an old version (the latest in pub.dev is 3.1.0), and also an old version of `geocoding_android` (the dep is 2.1.2, latest is 3.0.0).

```
├── geocoding 2.1.1
│   ├── geocoding_android 2.1.2
│   │   └── geocoding_platform_interface...
│   ├── geocoding_ios 2.1.1
│   │   └── geocoding_platform_interface...
│   └── geocoding_platform_interface 2.0.1
```

The platform interface API has changed in the git version, so that it's required to call `setLocale` rather than passing the locale in as a parameter.

### Expected results

It would be nice to get the pub.dev version up to date with git.

### Actual results

Deps are old.

### Code sample

N/A

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

2.1.1

### Flutter Doctor output

N/A

**Comment by TimHoogstrate** [comment]
@lukehutch,

Thanks for your issue. I'll label this as an enhancement.

Kind regards,
