### ISSUE TITLE
Android localization only works for country, not other levels

### ISSUE THREAD

**Issue by lukehutch** [Baseflow/flutter-geocoding#184]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geocoding/blob/main/geocoding/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS

### Steps to reproduce

On Android at least, on `geolocation` 2.1.1, passing a locale to the localizer only translates the country, not the other levels of the placemark.

For example, for a GPS location in California and the locale string `zh_HK`, "United States of America" is correctly rendered as "美國", but "California" is rendered simply as "California", rather than the correct "加州".

### Expected results

Placenames should be localized at at least the administrative area (state/province) level, if not the locality (city) level.

### Actual results

Placenames are only localized at the country level.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

2.1.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by mvanbeusekom** [comment]
Hi @lukehutch,

This is unfortunately out of our control. We simply pass the specified locale into the [geocoder SDK](https://developer.android.com/reference/android/location/Geocoder) provided by Android and return the results as is. There is no other processing involved from our side.

The free Android geocoder SDK has it's limitations, unfortunately they are not well documented by Google..
