### ISSUE TITLE
[Feature request]: Expose `Geocoder.isPresent` method on Android

### ISSUE THREAD

**Issue by lukehutch** [Baseflow/flutter-geocoding#194]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).

### Please select affected platform(s)

- [X] Android
- [ ] iOS

### Use case

The Android Geocoder class may or may not have a working backend. From [the docs](https://developer.android.com/reference/android/location/Geocoder):

> The Geocoder class requires a backend service that is not included in the core android framework. The Geocoder query methods will return an empty list if there no backend service in the platform. Use the `isPresent()` method to determine whether a Geocoder implementation exists.

I assume that in particular, any Google experience device (or Android builds that include Google Play Services) has a Geocoder backend based on the Google Maps API, whereas Android builds that do not include Google Play Services do not have this backend (but this is just a guess).

### Proposal

Can you please expose the `Geocoder.isPresent()` method in the Dart API?

### Specific requirements or considerations

N/A

**Comment by TimHoogstrate** [comment]
Fixed in (https://github.com/Baseflow/flutter-geocoding/pull/201/)
