### ISSUE TITLE
[Feature request]: iOS privacy manifest

### ISSUE THREAD

**Issue by yukihiro-numata** [Baseflow/flutter-geocoding#207]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).

### Please select affected platform(s)

- [ ] Android
- [X] iOS

### Use case

By Apple's guidelines, you must add an empty file even if you are not collecting anything.

### Proposal

According to the guidelines, add privacy_manifest_files.
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

### Additional information or context

See https://github.com/flutter/flutter/issues/131940 for context, but some kind of action will need to be taken.

**Comment by yukihiro-numata** [comment]
It appears that if you do not deal with, you may fail Apple's review after the spring of 2024.

**Comment by mvanbeusekom** [comment]
We have just released version 3.0.1 of the geocoding_ios package which included the required manifest file. More information can be found in PR #225.
