### ISSUE TITLE
[Bug]: localeIdentifier not working in iOS

### ISSUE THREAD

**Issue by tomasAlabes** [Baseflow/flutter-geocoding#208]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geocoding/blob/main/geocoding/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS

### Steps to reproduce

I believe this used to work recently.

```dart
final List<Placemark> placemarks = await placemarkFromCoordinates(
                52.36477, 4.88124,
                localeIdentifier: "en_US");
```

### Expected results

```
{
      // ...
      "country": "Netherlands", 
}
```

### Actual results

```
{
      // ...
      "country": "Nederland", 
}
```

### Code sample

<details><summary>Code sample</summary>

```dart
final List<Placemark> placemarks = await placemarkFromCoordinates(
                52.36477, 4.88124,
                localeIdentifier: "en_US");
```

</details>

### Version

2.2.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.3.1 23D60 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.4)
[✓] VS Code (version 1.86.2)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by Mohamed-Nagdy** [comment]
I face the same issue in both android and iOS I provide the locale (ar) and it give me back the result in English

**Comment by tomasAlabes** [comment]
@TimHoogstrate @mvanbeusekom this was introduced in this PR: https://github.com/Baseflow/flutter-geocoding/pull/205

Version 2.2.0 breaks the `localIdentifier` feature. See `geocoding.dart`: https://github.com/Baseflow/flutter-geocoding/pull/205/files#diff-2b11c3984a637300869b693b92f909a812bfb0d028ead4d7959f2f90b4348bcb
