### ISSUE TITLE
PlatformException(IO_ERROR, grpc failed, null, null)[Bug]: 

### ISSUE THREAD

**Issue by zhengxiangke** [Baseflow/flutter-geocoding#212]
### Please check the following before submitting a new issue.

- [ ] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geocoding/blob/main/geocoding/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS

### Steps to reproduce

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(IO_ERROR, grpc failed, null, null)
E/flutter (12578): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter (12578): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
E/flutter (12578): <asynchronous suspension>
E/flutter (12578): #2      GeocodingAndroid.placemarkFromCoordinates (package:geocoding_android/geocoding_android.dart:72:9)
E/flutter (12578): <asynchronous suspension>
E/flutter (12578): #3      _GeocodeWidgetState.build.<anonymous closure>.<anonymous closure> (package:geocoding_example/main.dart:81:29)
E/flutter (12578): <asynchronous suspension>

android

### Expected results

   final latitude = double.parse(_latitudeController.text);
                  final longitude = double.parse(_longitudeController.text);

                  placemarkFromCoordinates(latitude, longitude)
                      .then((placemarks) {
                    var output = 'No results found.';
                    if (placemarks.isNotEmpty) {
                      output = placemarks[0].toString();
                    }

                    setState(() {
                      _output = output;
                    });
                  });

### Actual results

返回地址

### Code sample

   final latitude = double.parse(_latitudeController.text);
                  final longitude = double.parse(_longitudeController.text);

                  placemarkFromCoordinates(latitude, longitude)
                      .then((placemarks) {
                    var output = 'No results found.';
                    if (placemarks.isNotEmpty) {
                      output = placemarks[0].toString();
                    }

                    setState(() {
                      _output = output;
                    });
                  });

### Screenshots or video

<img width="1439" alt="image" src="https://github.com/Baseflow/flutter-geocoding/assets/9394118/92e8143d-292b-4fb7-890a-20515a62b95f">

### Version

 geocoding: ^2.2.0

### Flutter Doctor output

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(IO_ERROR, grpc failed, null, null)
E/flutter (12578): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter (12578): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
E/flutter (12578): <asynchronous suspension>
E/flutter (12578): #2      GeocodingAndroid.placemarkFromCoordinates (package:geocoding_android/geocoding_android.dart:72:9)
E/flutter (12578): <asynchronous suspension>
E/flutter (12578): #3      _GeocodeWidgetState.build.<anonymous closure>.<anonymous closure> (package:geocoding_example/main.dart:81:29)
E/flutter (12578): <asynchronous suspension>

**Comment by TimHoogstrate** [comment]
Dear @zhengxiangke,

Thanks for your issue. I've looked into the issue and according to the README the following could be happening:

```
1. This plugin uses the free Geocoding services provided by the iOS and Android platforms. This means that there are restrictions to their use. More information can be found in the [Apple documentation for iOS](https://developer.apple.com/documentation/corelocation/clgeocoder) and the [Google documentation for Android](https://developer.android.com/reference/android/location/Geocoder).
   When a `PlatformException(IO_ERROR, ...)` gets thrown, most of the times it means that the rate limit has been reached.
2. The availability of the Google Play Services depends on your country. If your country doesn't support a connection with the Google Play Services, you'll need to try a VPN to establish a connection. For more information about how to work with Google Play Services visit the following link: https://developers.google.com/android/guides/overview 
```

Can you check if one of the issues may apply to your situation?

Kind regards,
