### ISSUE TITLE
[Bug]: `isPresent` takes `localeIdentifier` param, but does not use it

### ISSUE THREAD

**Issue by lukehutch** [Baseflow/flutter-geocoding#219]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geocoding/blob/main/geocoding/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [X] iOS

### Steps to reproduce

```dart
Future<bool> isPresent({
  String? localeIdentifier,
}) =>
    GeocodingPlatform.instance!.isPresent();
```

### Expected results

There should be no param to this method.

### Actual results

Param `localeIdentifier` is not used.

### Code sample

N/A

### Screenshots or video

N/A

### Version

2.2.1

### Flutter Doctor output

N/A

**Comment by TimHoogstrate** [comment]
Is Fixed in (https://github.com/Baseflow/flutter-geocoding/pull/222)
