### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by jonahmons** [Baseflow/flutter-geocoding#22]
Hi everyone, 

i try to run the "geocoding_platform_interface 1.0.1+1" from [pub.dev](https://pub.dev/packages/geocoding_platform_interface) but i get the error: 

`[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method locationFromAddress on channel flutter.baseflow.com/geocoding)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#2      MethodChannelGeocoding.locationFromAddress (package:geocoding_platform_interface/src/implementations/method_channel_geocoding.dart:29:46)`

I am not sure, what i did wrong. 
I want to get the cordinates of an address String:

`    List<Location> locations = await GeocodingPlatform.instance.locationFromAddress("Gronausestraat 710, Enschede");
`
first i try it with: 

`    List<Location> locations = await locationFromAddress("Gronausestraat 710, Enschede");
`

but the methode can not be found.

The import that i use is:

`import 'package:geocoding_platform_interface/geocoding_platform_interface.dart';`

Have you some ideas ? 
I see the other issues with the similar problem. but a restart dosnt work. 

Thank you :)

**Comment by flogaribal** [comment]
I think the package name is just `geocoding`

Just add the followinf dependency to your `pubspec.yaml` and it should work as expected:
```
geocoding: ^1.0.5 
```
Thus, the import should be:
```
import 'package:geocoding/geocoding.dart';
```
And the right way to get location is the first one you tried:
```
List<Location> locations = await locationFromAddress("Gronausestraat 710, Enschede");
```

**Comment by jonahmons** [comment]
Hey @flogaribal, thank you for your answer :) 

bevor i use `geocoding_platform_interface 1.0.1+1` 
 i try 
`geocoding: ^1.0.5 `

but i want to use ist on android, desktop (Linux and Windows) AND web, so i try `geocoding_platform_interface 1.0.1+1` . 
I have understood that `geocoding_platform_interface 1.0.1+1`  also supports WEB. 
I am little bit irritated that both plugings reference on the same gitrepro, but i think `geocoding_platform_interface 1.0.1+1` is a clone of `geocoding: ^1.0.5 `

**Comment by flogaribal** [comment]
Oh ok sorry I did not know that :/ 
Then I cannot help you more, sorry

**Comment by mvanbeusekom** [comment]
@jonahmons, I am afraid you understood things wrong. The geocoding plugin doesn't support web as of yet. 

The geocoding plugin is build according to the [Federated plugin](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#federated-plugins) architecture (as recommended by Google). This means that we have a package `geocoding_platform_interface` that defines a contract which can be implemented by other packages to add support for specific platforms. 

The geocoding plugin is the app facing package which federates calls to the appropriate platform implementation. As mentioned at the moment I have only implemented platform implementations for Android and iOS. But the architecture is ready to add additional platform implementations (like web, linux, macos or windows) but I didn't have time to do so as of yet. 

Please take into consideration that I need to maintain this project in my spare time. So I am hoping for the community to chime in and help extend the plugin.

**Comment by jonahmons** [comment]
Thank you,

I was a little bit irritated 😃, but i understand :)

I was trying to use the library in my bachelor thesis, but i think i have to use an other way.

If i have time after the thesis, i will try to update this library.

Best regards :)

**Comment by mvanbeusekom** [comment]
Closing this issue per discussion above
