### ISSUE TITLE
[Feature request]: Older synchronous Android code can be removed

### ISSUE THREAD

**Issue by lukehutch** [Baseflow/flutter-geocoding#220]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).

### Please select affected platform(s)

- [X] Android
- [X] iOS

### Use case

I filed #195 requesting for the newer Android async geocoder API to be supported in API > 33. Thanks for adding that!

However, I noticed that since release 2.0.6 of `flutter-geocoding`, `compileSdkVersion` has actually been set to `33` on Android.

As I'm sure you know, there's no going back from API 33 at this point, because all new app store releases (and even app store updates) of Android apps have to at a minimum be built for API 33:

https://apilevels.com/

This means that guarded sections like the following are not needed, and all older Android code (before `TIRIMASU`) can be removed:

https://github.com/Baseflow/flutter-geocoding/blob/main/geocoding_android/android/src/main/java/com/baseflow/geocoding/Geocoding.java#L58

### Proposal

Remove all old code

### Specific requirements or considerations

--

**Comment by TimHoogstrate** [comment]
Dear @lukehutch,

I think this is not true. Even though the compileSdkVersion is e.g. > 33, the software can still run on a < 33 SDK device.

Kind regards,

**Comment by lukehutch** [comment]
Got it, thanks for clarifying.
