### ISSUE TITLE
[Bug]: localization not working also setLocaleIdentifier ihas not been implementated

### ISSUE THREAD

**Issue by NabeelAbid1812** [Baseflow/flutter-geocoding#224]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geocoding/blob/main/geocoding/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [X] iOS

### Steps to reproduce

i,m facing issue when i change my mobile language and use placemarkFromCoordinates function with parameter localeIdentifier :'en' but it gives me a response in Arabic

### Expected results

i,m facing issue when i change my mobile language and use placemarkFromCoordinates function with parameter localeIdentifier :'en' but it gives me a response in Arabic

### Actual results

actual result should be in english

### Code sample

 final placemarks = await placemarkFromCoordinates(position.latitude, position.longitude,localeIdentifier: 'en');

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>
n/a

### Version

2.2.2

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.13.6, on macOS 13.6 22G120 darwin-arm64, locale en-PK)
    • Flutter version 3.13.6 on channel stable at /Users/macbook/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (6 months ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

**Comment by TimHoogstrate** [comment]
This is solved in version 3.0.0. You should set the locale first and then call the functions without the locale parameter.

kind regards,
