### ISSUE TITLE
 Privacy manifest file in geocoding_ios 3.0.1 and update status of flutter-geocoding plugin

### ISSUE THREAD

**Issue by Ultranmus** [Baseflow/flutter-geocoding#227]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geocoding/blob/main/geocoding/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS

### Your question

I noticed that the geocoding_ios version 3.0.1 has a Privacy manifest file. However, the latest version of geocoding still uses geocoding_ios version 3.0.0. I'm curious about when the geocoding plugin will be updated to include the latest version of geocoding_ios.

### Version

3.0.0

**Comment by mvanbeusekom** [comment]
Hi @Ultranmus,

As with the geolocator plugin (see [comment](https://github.com/Baseflow/flutter-geolocator/issues/1470#issuecomment-2012265705)) the `geocoding` package use the constraint `^3.0.0`. This means the latest version of `geolocator_ios` will automatically be included.
