### ISSUE TITLE
[Question]: Geocoding Build error

### ISSUE THREAD

**Issue by Raaaphz** [Baseflow/flutter-geocoding#228]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geocoding/blob/main/geocoding/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS

### Your question

The geolocator package works perfectly, but when i write "geocoding: ^3.0.0" my app doesnt build anymore, and i get this error in the following image
![image](https://github.com/Baseflow/flutter-geocoding/assets/145306709/85d9e43d-696b-4d59-9c2a-84a34d5d4ec7)

im not so good with that "technical english" at all, so i dont understand what i did wrong

### Version

3.0.0

**Comment by mvanbeusekom** [comment]
Hi @Raaaphz,

The error isn't really clear, but it seems to be related with Android 33. There are a few things you can try:

1. Check the `compileSdkVersion` in the `android/app/build.gradle` file. This should be set to `33` or higher. If this is not the case, set it to 33 and run or build the application again.
2. Run `flutter clean` in the console and "Invalidate caches" in Android Studio / IntelliJ (this option can be found in the "File" menu). Try to run or build the application again.
3. If the error persists, check if you have the Android 33 SDK installed using the "SDK Manager" (in Android Studio / IntelliJ, see "Tools -> SDK Manager").

If these steps don't work please provide the complete output of the `flutter doctor -v` command and the complete error log (running `flutter run -v` will provide verbose error logging which includes a lot more details that might help.
