### ISSUE TITLE
[Question]: PlatformException(IO_ERROR, fsmr: DEADLINE_EXCEEDED)

### ISSUE THREAD

**Issue by zhubarb** [Baseflow/flutter-geocoding#229]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geocoding/blob/main/geocoding/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS

### Your question

This package used to work well in my Android app. However I recently started getting: "`[log] Failed to get place name: PlatformException(IO_ERROR, fsmr: DEADLINE_EXCEEDED: deadline exceeded after 4.904684844s. Name resolution delay 0.070036719 seconds. [closed=[], open=[[buffered_nanos=4905356874, waiting_for_connection]]], null, null)`". Not sure whether this is due to usage limits, the links provided (https://developer.android.com/reference/android/service/restrictions/package-summary) do not give information.

geocoding: ^3.0.0
    minSdk 26
    targetSdk 34
    compileSdk 34

### Version

3.0.0

**Comment by mvanbeusekom** [comment]
Hi @zhubarb,

The `DEADLINE_EXCEEDED` is an internal error of Android's [Geocoder SDK](https://developer.android.com/reference/android/location/Geocoder) (which is what the geocoding plugin uses to convert coordinates into address information and vice versa). 

Android's [Geocoder SDK](https://developer.android.com/reference/android/location/Geocoder) internally makes HTTP requests to Googles services todo the lookup, the `DEADLINE_EXCEEDED` means that the Google services didn't respond in time. 

Unfortunately the [Geocoder SDK](https://developer.android.com/reference/android/location/Geocoder) doesn't provide any control on timeout settings so there is not much we can do about the error. If you require more stable services, consider using a premium solution.
