### ISSUE TITLE
PlatformException (PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates (latitude: 30.867672, longitude: 122.209517)., null, null))

### ISSUE THREAD

**Issue by yosef406** [Baseflow/flutter-geocoding#23]
## 🐛 Bug Report

the reason is unknown, it was working half an hour ago, this problem happened before but it stopped for a few days and now it came back, my device is connected to the enternet (android emulator on windows pc)
also "try{}catch{}" isnt stoping the problem the app crashes.

![image](https://user-images.githubusercontent.com/63299984/97601935-64a27000-1a13-11eb-920c-14c93a9edce5.png)

### Expected behavior
getting the place marks

### Reproduction steps
unknown

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by Scott1803** [comment]
Exact same thing happened to me, did you end up finding a solution?

**Comment by yosef406** [comment]
Yes 
Not sure what is the problem, but I ended up making a new android emulator(a new emulated device) with android 29 and it worked fine.

**Comment by yosef406** [comment]
update.
i used the old emulator (android 30) and at first it didnt work, with the same problem, then in the imulator i turned off the wifi and it worked, and when turning back the wifi it worked again.

**Comment by KyawThet-Naing** [comment]
same error

**Comment by lailai0715** [comment]
@yosef406 Can you reopen this issue again? My app will appear this issue when calling too much getCurrentPosition(). Thank you.

**Comment by tinvyhx** [comment]
Same issue ,on realy device Sony G8342 with android version 9

**Comment by DevTiago** [comment]
Same here.. using Android Tiramisu API 33 x86_64.

When using Android R API 30, it works fine.

**Comment by kbram** [comment]
try to add localeIdentifier parameter. It's working for me. like be this code.

placemarkFromCoordinates(position.latitude, position.longitude,localeIdentifier: "en");

**Comment by MrBooring** [comment]
I think someone needs to handle the exception please consider this test case 
if a device lost the internet connection before getting the location, then the app will stop in an exception 

for the solution, I have tried connectivity_plus to check for an internet connection still am not able to handle this issue sorry I cannot provide a code for reference

**Comment by rangerisrael** [comment]
![image](https://github.com/Baseflow/flutter-geocoding/assets/38226544/90856cc8-591e-4069-8971-2071dff92dd6)

**Comment by rangerisrael** [comment]
![image](https://github.com/Baseflow/flutter-geocoding/assets/38226544/225fe124-52c6-4e04-b528-553bf0fe6f04)
