### ISSUE TITLE
PlatformException(IO_ERROR, Service not Available, null, null)[Question]: 

### ISSUE THREAD

**Issue by Omo-oba18** [Baseflow/flutter-geocoding#232]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geocoding/blob/main/geocoding/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [x] iOS

### Your question

I have implemented the geocoding library some months ago and it was working fine, I could get the location successufully but now, I am having some Service not available error I wonder why this error occured now! 

`Future<void> _getAddressFromLatLng(Position position) async {

    try {
      List<Placemark> placemarks = await placemarkFromCoordinates(
        position.latitude,
        position.longitude,
        //   52.2165157, 6.9437819
      );

      if (placemarks.isNotEmpty) {
        Placemark place = placemarks[0];
        _currentAddress =
            '${place.street}, ${place.subLocality}, ${place.subAdministrativeArea}, ${place.postalCode}';
      }
    } on PlatformException catch (e) {
      // Handle specific platform exceptions
      logger.e("Platform Exception: $e");
      _currentAddress = "Address Unavailable";
    } catch (e) {
      // Catch any other exceptions
      logger.e("Error fetching address: $e");
      _currentAddress = "Address Unavailable";
    }
  }
`

I added the google map API key in the AndroidManifest.xml and the ACCESS_FINE_LOCATION is added too!
Months ago, I was testing with Samsung galaxy s9+, but nowadays, I am using Android 8.1 (oreo)

Can someone assist me? I want to know what I am doing wrong!

![android-manifest](https://github.com/Baseflow/flutter-geocoding/assets/130931422/f7ad695a-cc25-487a-85c1-44461ee7af90)

Error:
`
I/flutter (14829): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (14829): │ #0   LocationProvider._getAddressFromLatLng (package:stemir/src/provider/location_provider.dart:96:14)
I/flutter (14829): │ #1   <asynchronous suspension>
I/flutter (14829): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (14829): │ ⛔ Platform Exception: PlatformException(IO_ERROR, Service not Available, null, null)
I/flutter (14829): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────`

### Version

3.0.0

**Comment by yubraja** [comment]
I am also facing this issue...

**Comment by TimHoogstrate** [comment]
@Omo-oba18,

Did you resolve the issue?

Kind regards,
