### ISSUE TITLE
Find Location from Zip Code

### ISSUE THREAD

**Issue by ShahzaibH414** [Baseflow/flutter-geocoding#237]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geocoding/blob/main/geocoding/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [X] iOS

### Your question

I want to know that is it possible to find the locations based on the zip Code. i have read the documentation it says it can do this. but i am unabke to find it in the code or implementation

### Version

3.0.0

**Comment by TimHoogstrate** [comment]
Dear @ShahzaibH414,

Can you elaborate a bit on the subject? What do you mean bij location... Placemark, or coordinate? It seems to be possible. 

Kind regard,
