### ISSUE TITLE
[Question]: The rate limit for this package depends on total users of my application or like per user of my app?

### ISSUE THREAD

**Issue by sudhanshugaur4** [Baseflow/flutter-geocoding#238]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geocoding/blob/main/geocoding/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [X] iOS

### Your question

[Question]: The rate limit for this package depends on total users of my application or like per user of my app.. I am asking this because suppose I have 1 million downloads but all calling this API once, so for like daily 10k installs 10k requests will be there, so will this package be free. Because one user is calling this API once only?

### Version

3.0.0

**Comment by TimHoogstrate** [comment]
Dear @sudhanshugaur4,

Thanks for your question. It seems that it is related to the total requests of your app (not per user). 

Kind regards,
