### ISSUE TITLE
Will the plugin work with the compileSdkVersion 29?

### ISSUE THREAD

**Issue by yulkin2002** [Baseflow/flutter-geocoding#24]
also, the link regarding the full list of android. dependencies in the readme section #3 is not working. could you provide the working link please?

**Comment by kevkanae** [comment]
I've used compileSdkVersion 28 and 29, and both worked perfectly fine in fetching the addresses from coordinates.
Flutter SDK Version: 1.22.4

> my app was on compileSdkVersion 29 but changed to 28 as it was not getting addresses from coordinates.
