### ISSUE TITLE
placemarkFromCoordinates erratically fails or causes an error exception

### ISSUE THREAD

**Issue by kalmigs** [Baseflow/flutter-geocoding#28]
## 🐛 Bug Report

placemarkFromCoordinates sometimes fails and it seems to me it is random. I cannot reproduce it consistently. Can I get some help?

Note: occured in emulator, haven't encountered it in a real device but I will update this if it shows there also.

As it will successfully get an address the next try, my workaround for now is as below (kinda ugly but works for now):

```dart
    List<Placemark> placeMarks;
    try {
      placeMarks = await placemarkFromCoordinates(lat, long);
    } catch (e) {
      await Future.delayed(Duration(milliseconds: 300));
      try {
        placeMarks = await placemarkFromCoordinates(lat, long);
      } catch (e) {
        showSnackBar(2, 'Address was not retrieved, please fill out manually');
      }
    }
```

### Expected behavior

Should consistently get address from coordinates

### Reproduction steps

```dart
 List<Placemark> placeMarks = await placemarkFromCoordinates(lat, long);
```

### Configuration

**Version:** 1.0.5

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
What is the error that you receive? 

Also note that the geocoding plugin relies on the free services provided by Apple and Google which are available through SDKs that they ship with their platforms. These free services are rate-limited, which might be the reason you are not able to reproduce the error consistently and why you (up to now) only experience it in the emulator (assuming you mostly test your software on the emulator which has a bigger change on reaching the rate-limit).

Although Apple and Google don't give a lot of details about these limits, more information can be found [here](https://developer.apple.com/documentation/corelocation/clgeocoder?language=objc) (Apple) and [here](https://developer.android.com/reference/android/location/Geocoder) (Google).

**Comment by Jaystiqs** [comment]
I am facing the same problem.  I get the error...
flutter: PlatformException(IO_ERROR, Error Domain=kCLErrorDomain Code=2 "(null)", null, null)

Over and over again until the application runs out of memory

**Comment by mvanbeusekom** [comment]
@Jaystiqs you will receive this error from Apple when you exceeded your request rate limit. Please carefully read the documentation [here](https://developer.apple.com/documentation/corelocation/clgeocoder?language=objc) (specifically the "Tips for Using a Geocoder Object" section). 

Apple and Google provide some geocoding features free of charge but at restrictions (mostly rate-limited). Meaning you can only do a x amount of requests in a certain time limit. Unfortunately both Apple and Google don't provide clear details on what those time limits are so I cannot really provide any more detailed feedback on this.

**Comment by kalmigs** [comment]
Apologies I haven't replied to this. Below is the error I also got. I think this is not exceeding the request rate limit as I only encounter this during 1st time using the package from start of app. but in succeeding request it will get the address.

error: 
```console
PlatformException (PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates (latitude: 40.5012879, longitude: -73.9113468)., null, null))
```
error code: 
```console
IO_ERROR
```

error message: 
```console
A network error occurred trying to lookup the supplied coordinates (latitude: 10.299458, longitude: 123.896296).
```

**Comment by manny-e1** [comment]
> Apologies I haven't replied to this. Below is the error I also got. I think this is not exceeding the request rate limit as I only encounter this during 1st time using the package from start of app. but in succeeding request it will get the address.
> 
> error:
> 
> ```
> PlatformException (PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates (latitude: 40.5012879, longitude: -73.9113468)., null, null))
> ```
> 
> error code:
> 
> ```
> IO_ERROR
> ```
> 
> error message:
> 
> ```
> A network error occurred trying to lookup the supplied coordinates (latitude: 40.5012879, longitude: -73.9113468).
> ```

I ran into the exact same error. did you find any solution?

**Comment by kalmigs** [comment]
@manny-e1, I only encounter this in emulator so far, but what i did is just call "placeMarks = await placemarkFromCoordinates(lat, long);" again in catch on a try-catch statement.

**Comment by manny-e1** [comment]
> @manny-e1, I only encounter this in emulator so far, but what i did is just call "placeMarks = await placemarkFromCoordinates(lat, long);" again in catch on a try-catch statement.

@kalmigs i also tried it in a try-catch block that day and it worked for me too. Thanks for the response though.

**Comment by mvanbeusekom** [comment]
@kalmigs, @manny-e1, this error is triggered by the Android sub-system when it cannot contact Google's backend services. This can have multiple reasons:

1. Your device doesn't have a (good) internet connection;
2. Google's services are down (or overloaded);
3. Some internet providers (or country firewalls) don't allow access to the Google Play Services.

Unfortunately this is not something I have any influence on and cannot really do anything to make it better. Best is (like you already doing) to catch the exception and try again later.
