### ISSUE TITLE
Administrative area US abbriviation

### ISSUE THREAD

**Issue by hetkpatel** [Baseflow/flutter-geocoding#3]
Are only the states in the US abbreviated or are there other countries where the admin area label is shortened?

**Comment by mvanbeusekom** [comment]
Hi @hetkpatel, unfortunately I don't really have a clear answer to this question. The reason being that the way the states are formatted depends on the implementation of the geocoding SDK of the target platform (and probably the locale you use). Under the hood the Geocoding plugin uses the [CLGeocoder](https://developer.apple.com/documentation/corelocation/clgeocoder) SDK for iOS and the [Geocoder](https://developer.android.com/reference/android/location/Geocoder) SDK on Android and simply forwards their results back to the Dart side. So we don't really control how the address information is formatted.

Maybe you can find more information in the iOS or Android documentation regarding the native results of the reverse geocode call:

- iOS will return an instance of the [CLPlacemark](https://developer.apple.com/documentation/corelocation/clplacemark) class;
- Android will return an instance of the [Address](https://developer.android.com/reference/android/location/Address) class.

Hope this helps.

**Comment by hetkpatel** [comment]
Sounds good. Thank you!
