### ISSUE TITLE
Null Safety support

### ISSUE THREAD

**Issue by EDnny12** [Baseflow/flutter-geocoding#37]
### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
I have just release version 2.0.0 which is opted in to null safety, you can download it from pub.dev now: https://pub.dev/packages/geocoding

Many thanks to @grahamsmith, @dariotrombello and @JDDV for helping out!
