### ISSUE TITLE
Incompatible with Flutter Fire 1.0.0 due to unused url_launcher dependency

### ISSUE THREAD

**Issue by grahamsmith** [Baseflow/flutter-geocoding#38]
## 🐛 Bug Report

Incompatible with Flutter Fire 1.0.0 / null safe releases.

Due to the dependencies using from what I can see is an unused package dependency of: url_launcher: ^5.4.11

In the main geocoding library I couldn't see any code that would use the url_launcher. It is used in the example but that has its own separate pubspec.yaml.

### Expected behavior

Remove the url_launcher dependency as it is unused and therefore fixes the incompatibility.

### Reproduction steps

N/A

### Configuration

**Version:** 1.0.5

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by grahamsmith** [comment]
@mvanbeusekom - I can PR this if you agree with the assessment. Would be good to get this sorted as its blocking some other things in other projects but also want to help rather just complain.

**Comment by mvanbeusekom** [comment]
That would be awesome. I think the `url_launcher` is used in the `example` project so maybe check if it exists there in the `example/pubspec.yaml`. But it should indeed be removed from the root `pubspec.yaml`. 

Looking forward to your PR!

**Comment by jlnrrg** [comment]
As far as I am concerned, the **geocoding_platform_interface** also needs **plugin_platform_interface: ^2.0.0**

```
Because every version of geocoding from git depends on geocoding_platform_interface ^1.0.1 which depends on plugin_platform_interface ^1.0.2, every version of geocoding from git requires plugin_platform_interface ^1.0.2.
And because firebase_core >=1.0.0 depends on firebase_core_platform_interface ^4.0.0 which depends on plugin_platform_interface ^2.0.0, geocoding from git is incompatible with firebase_core >=1.0.0.
So, because test_project depends on both firebase_core ^1.0.0 and geocoding from git, version solving failed.
```

**Comment by wesleyguirra** [comment]
Incompatible with firebase_messaging now.
