### ISSUE TITLE
'Placemark' isn't a type

### ISSUE THREAD

**Issue by ndhbr** [Baseflow/flutter-geocoding#4]
## 🐛 Bug Report

I am currently upgrading from version 5 of the Geolocator to version 6 and since the geocoding is now handled in an extra plugin I have installed this plugin.

Unfortunately the class "Placemark" is unknown, although the plugin is included. The method placemarkFromCoordinates(...) is known.

### Expected behavior

"placemarkFromCoordinates(...)" returns a list of elements of the known class Placemark.

### Reproduction steps

Install this plugin and try to execute this line:
`List<Placemark> placemarks =
          await placemarkFromCoordinates(point.latitude, point.longitude);`

### Configuration

**Version:** 1.0.1

**Comment by mvanbeusekom** [comment]
@ndhbr the `Placemark` class is defined in the `geocoding_platform_interface` package (which the geocoding package depends on and is automatically installed). Your issue should be solved if you add the following import in the file where you need the `Placemark` class:

``` dart
import 'package:geocoding_platform_interface/geocoding_platform_interface.dart';
```

**Comment by ndhbr** [comment]
Unfortunately VSCode did not find the position automatically.

But thanks. That solved the problem.

Also thanks for developing these plugins! Keep up the good work.
