### ISSUE TITLE
Can anyone help me with this

### ISSUE THREAD

**Issue by hemanthkb97** [Baseflow/flutter-geocoding#50]
## 🐛 Bug Report

Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Xcode build done.                                           19.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/shashikumar/HealthAssist/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-7.0.3/ios/Classes/GeolocatorPlugin.m:199:31: error: unexpected interface name 'NSURL': expected expression
                          openURL:NSURL URLWithString options:UIApplicationOpenSettingsURLString completionHandler:nil];
                                  ^
    1 error generated.
    /Users/shashikumar/HealthAssist/flutter/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.0/ios/Classes/Extensions/CLPlacemarkExtensions.m:22:18: warning: 'addressDictionary' is deprecated: first deprecated in iOS 11.0 - Use @properties [-Wdeprecated-declarations]
            if (self.addressDictionary != nil) {
                     ^
    In module 'CoreLocation' imported from /Users/shashikumar/HealthAssist/flutter/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.0/ios/Classes/Extensions/CLPlacemarkExtensions.h:10:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLPlacemark.h:73:63: note: 'addressDictionary' has been explicitly marked deprecated here
    @property (nonatomic, readonly, copy, nullable) NSDictionary *addressDictionary API_DEPRECATED("Use @properties", macos(10.8, 10.13), ios(5.0, 11.0), watchos(1.0, 4.0));
                                                                  ^
    /Users/shashikumar/HealthAssist/flutter/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.0/ios/Classes/Extensions/CLPlacemarkExtensions.m:23:29: warning: 'addressDictionary' is deprecated: first deprecated in iOS 11.0 - Use @properties [-Wdeprecated-declarations]
                street = [[self addressDictionary] objectForKey:(NSString *)kABPersonAddressStreetKey];
                                ^
    In module 'CoreLocation' imported from /Users/shashikumar/HealthAssist/flutter/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.0/ios/Classes/Extensions/CLPlacemarkExtensions.h:10:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLPlacemark.h:73:63: note: property 'addressDictionary' is declared deprecated here
    @property (nonatomic, readonly, copy, nullable) NSDictionary *addressDictionary API_DEPRECATED("Use @properties", macos(10.8, 10.13), ios(5.0, 11.0), watchos(1.0, 4.0));
                                                                  ^
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLPlacemark.h:73:63: note: 'addressDictionary' has been explicitly marked deprecated here
    /Users/shashikumar/HealthAssist/flutter/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.0/ios/Classes/Extensions/CLPlacemarkExtensions.m:23:73: warning: 'kABPersonAddressStreetKey' is deprecated: first deprecated in iOS 9.0 - use CNPostalAddress.street [-Wdeprecated-declarations]
                street = [[self addressDictionary] objectForKey:(NSString *)kABPersonAddressStreetKey];
                                                                            ^
    In module 'AddressBook' imported from /Users/shashikumar/HealthAssist/flutter/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.0/ios/Classes/Extensions/CLPlacemarkExtensions.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/System/Library/Frameworks/AddressBook.framework/Headers/ABPerson.h:113:29: note: 'kABPersonAddressStreetKey' has been explicitly marked deprecated here
    AB_EXTERN const CFStringRef kABPersonAddressStreetKey AB_DEPRECATED("use CNPostalAddress.street");
                                ^
    3 warnings generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.
Exited (sigterm)

### Configuration

**Version:** 1.x

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by meeftah** [comment]
same here...there is a lot deprecated issues, it says "deprecated in iOS 9.0"
