### ISSUE TITLE
Flutter Web support

### ISSUE THREAD

**Issue by kevinrimml** [Baseflow/flutter-geocoding#68]
## 🚀 Feature Requests
Hey guys, just wanted to know if you are planning to implement flutter web support in the near future? Thanks in advance and best regards :)

**Comment by JDDV** [comment]
Hi @kevinrimml, Thanks you for your question, I would like you to have a look at #69, this is an proposal about web support for the `geocoding` plugin. The thing is that Geocoding API's are free to use, but to a certain extend, and that makes it difficult for us. Android and Apple have their own geocoding service available for mobile phones and are completely free to use (as long as they don't get abused), but for web this is different.

This is all explained in the proposal, and it would help us out a lot if you could react on the proposal so we know what way to go with the web support for the plugin.

Thanks in advance!
