### ISSUE TITLE
placemarkFromCoordinates in isolate

### ISSUE THREAD

**Issue by anasmano** [Baseflow/flutter-geocoding#71]
Hello,

I  got  error when calling placemarkFromCoordinates in Isolate.

Here's the error

E/flutter (20127): [ERROR:flutter/runtime/dart_isolate.cc(1137)] Unhandled exception:
E/flutter (20127): Null check operator used on a null value
E/flutter (20127):     MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
E/flutter (20127):       MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
E/flutter (20127):       MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
E/flutter (20127):       MethodChannelGeocoding.placemarkFromCoordinates (package:geocoding_platform_interface/src/implementations/method_channel_geocoding.dart:56:44)
E/flutter (20127):       placemarkFromCoordinates (package:geocoding/geocoding.dart:44:32)

Can you give me a solution ?

**Comment by temirfe** [comment]
did you solve it? I have the same problem

**Comment by mvanbeusekom** [comment]
Unfortunately this will not work as method channels are not setup to work in isolates. This is a limitation on Flutter, not on the part of the geocoding plugin.

**Comment by abdullahalamodi** [comment]
> Hello,
> 
> I got error when calling placemarkFromCoordinates in Isolate.
> 
> Here's the error
> 
> E/flutter (20127): [ERROR:flutter/runtime/dart_isolate.cc(1137)] Unhandled exception: E/flutter (20127): Null check operator used on a null value E/flutter (20127): MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86) E/flutter (20127): MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36) E/flutter (20127): MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12) E/flutter (20127): MethodChannelGeocoding.placemarkFromCoordinates (package:geocoding_platform_interface/src/implementations/method_channel_geocoding.dart:56:44) E/flutter (20127): placemarkFromCoordinates (package:geocoding/geocoding.dart:44:32)
> 
> Can you give me a solution ?


I think you tried to run it on isolate because it's freezer the main thread  

but here is a great solution 
https://github.com/Baseflow/flutter-geocoding/issues/58#issuecomment-891315068
