### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by A-Aziz0** [Baseflow/flutter-geocoding#72]
### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [✔️ ] :desktop: windows

**Comment by Ronjack** [comment]
yeah desktop + web support would be greate!

**Comment by JeroenWeener** [comment]
Hi @A-Aziz0 and @Ronjack, thank you for reaching out!

The Android and iOS implementations make use of Google and Apple geocoding APIs that are available for free, although rate limited.

We would consider supporting Windows if that platform provides a similar API. Would you happen to know whether such an API exists?
