### ISSUE TITLE
GeocodingPlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by shaunhossain** [Baseflow/flutter-geocoding#76]
## 🔙 Regression

  

Note: /Users/jouleslabs/AndroidStudioProjects/flutter/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.1/android/src/main/java/com/baseflow/geocoding/GeocodingPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.

### Configuration

**Version:** 7.7.1

**Platform:** 

- [x] :robot: Android

**Comment by kamaludin21** [comment]
same issues

**Comment by cyiboy** [comment]
having same issue, Any fix

**Comment by massilva** [comment]
same issue

**Comment by BRSPRO** [comment]
the same issue please help with the solution

**Comment by CostierLucas** [comment]
any news ?

**Comment by Emanuelguantay** [comment]
same issue

**Comment by Chandio763** [comment]
facing same issue, did anyone figured out how to resolve?

**Comment by lensbreak** [comment]
same issue still here

**Comment by kalpanadh** [comment]
same issue,any solution?

**Comment by knighdda** [comment]
all i had to do is pub get ,then my project worked

**Comment by mvanbeusekom** [comment]
This issue has been resolved in version 2.0.3. Not that the message is a simple warning and could always be safely ignored. As of 2.0.3 we suppress the warning (as that particular code on exists to be backwards compatible).

**Comment by al-fahad-bd** [comment]
Facing the same issue in 2.1.0 version.

**Comment by nadhiroov** [comment]
still not solved?

**Comment by GiulioWecove** [comment]
Same issue in 2.1.1
