### ISSUE TITLE
MissingPluginException(No implementation found for method placemarkFromCoordinates on channel flutter.baseflow.com/geocoding)

### ISSUE THREAD

**Issue by Limvunhoy** [Baseflow/flutter-geocoding#80]
## 🔙 Regression

I got this error exception when trying to Add Flutter to Existing Native App (iOS)

### Configuration
- add flutter app as framework into existing iOS App (Native Swift)

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS

**Comment by vbabaria** [comment]
i get same error running on android

**Comment by sh1l0n** [comment]
Still happening in 2.0.2, is any extra step needed to configurate?

Thats the code, are valid coordinates and is running on simulator iOS 14.4
```
List<Placemark> placemarks = await placemarkFromCoordinates(latitude, longitude);
print(placemarks);
```

There is the error
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method placemarkFromCoordinates on channel flutter.baseflow.com/geocoding)
#0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:165
<asynchronous suspension>
#1      MethodChannelGeocoding.placemarkFromCoordinates (package:geocoding_platform_interface/src/implementations/method_channel_geocoding.dart:56:24)
<asynchronous suspension>
```

**Comment by ahaaje** [comment]
I get the same error on 2.0.4 testing on Android simulator. The code compiles, but this is thrown at runtime

`MissingPluginException(No implementation found for method placemarkFromCoordinates on channel flutter.baseflow.com/geocoding)`

The code in question using valid coordinates

```dart
import 'package:geocoding/geocoding.dart'; 

/// ...

List<Placemark> placemarks = await placemarkFromCoordinates(
          _currentPosition!.latitude, _currentPosition!.longitude,
          localeIdentifier: 'no_NO');
```

**Comment by ahaaje** [comment]
I solved this by setting `targetSdkVersion=31` and `compileSdkVersion=31`. The error then went away and an address was returned

**Comment by ps6067966** [comment]
In Flutter version 3.7.11 and dart version 2.19.6  compile sdk version 33 
I'm also facing same issue.

**Comment by i-brain** [comment]
still getting this issue on ios simulator any updates?

**Comment by i-brain** [comment]
It seems that I solved this issue by calling the function after the map swipe animation ended.

 FlutterMap(
            options: MapOptions(
               onMapEvent: (event) {
                if (event is MapEventFlingAnimationEnd) {
                   List<Placemark> placemarks = await placemarkFromCoordinates(latitude,longitude,);
                }
              },

**Comment by mvanbeusekom** [comment]
This issue usually happens when the plugin is accessed before the Flutter engine had time to register all plugins. Make sure that the methods are not accessed before the `runApp` method of your Flutter application is called (especially in Flutter add-to-app applications).

If for some reason you do need to access the Geocoding API before the `runApp` method is called, make sure to first call the `WidgetFlutterBindings.ensureInitialized()` method before accessing the Geocoding API.

**Comment by Shaham-Ahammed** [comment]
> I had the same issue after calling the api several times. Now I only call it after the previous call ends. It seems working.

this one helped me to solve the issue
