### ISSUE TITLE
Include vertical accuracy on the Position model

### ISSUE THREAD

**Issue by yusefasjana** [Baseflow/flutter-geocoding#82]
## 🚀 Feature Requests
I'm working on migrating an existing app to flutter and I'm using the geocoding plugin. One of the fields that we store from native Android/IOS is `verticalAccuracy` which I noticed the geocoding plugin omits on the Position model. it would be awesome if this value could be included on the response

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by TimHoogstrate** [comment]
Dear @yusefasjana,

It looks like this is currently part of the Gecoding plugin by the property `altitudeAccuracy` in the Position object.

Kind regards,
