### ISSUE TITLE
Unhandled Exception: Could not find any result for the supplied address or coordinates.

### ISSUE THREAD

**Issue by ChurikiTenna** [Baseflow/flutter-geocoding#86]
## 🐛 Bug Report

locationFromAddress() fail with Unhandled Exception when the locations of the supplied address does not exist.

### Expected behavior

return empty locations

### Reproduction steps

Enter on existence address on the 'address' field.
List<Location> locations = await locationFromAddress(address).timeout(Duration(seconds: 3));

### Configuration

**Version:** geocoding: ^2.0.1

**Platform:** 
- iphone: iOS 15.2

Not sure if this is a bug or an expected behavior. 
If there is any workaround, I would love to know!

Thank you in advance.

**Comment by mvanbeusekom** [comment]
Hi @ChurikiTenna, 

This would be a feature request. We designed the service to throw a `NoResultFoundException` and not return an empty list. We felt the `NoResultFoundException` was more explicit in informing developers what is happening. It is easy to handle by wrapping it in a try...catch block.
