### ISSUE TITLE
Returning Null value.

### ISSUE THREAD

**Issue by tictechAbin** [Baseflow/flutter-geocoding#92]
## 🐛 Bug Report

The function placemarkFromCoordinates is returning null value as i pass Coordintes to the function.
Expected to return list of placemarks.

**Comment by lvyandev** [comment]
I got this issue too, it happened when calling `placemarkFromCoordinates` multiple times during short time.

**Comment by feriyalsusanto** [comment]
Hi, I'm curious are you already find the workaround for this issue?

**Comment by andreisas06** [comment]
Hello @tictechAbin , thank you for submitting the issue. To better understand the problem you're facing, could you please provide a code sample related to the issue? This would greatly help in diagnosing the problem and providing an appropriate solution.
