### ISSUE TITLE
Feature Request: Provide Placemark type

### ISSUE THREAD

**Issue by vladaman** [Baseflow/flutter-geocoding#93]
## 🚀 Feature Requests

It would be good to also include in Placemark type. Google returns if it's postal_code or administrative area but it's not part of Placemark object.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by TimHoogstrate** [comment]
Dear @vladaman,

Can you please elaborate a bit on the subject. I see that the plugin passes through a lot of information regarding the address information. Like e.g.: 

```
        placemark.put("name", address.getFeatureName());
        placemark.put("street", street);
        placemark.put("isoCountryCode", address.getCountryCode());
        placemark.put("country", address.getCountryName());
        placemark.put("thoroughfare", address.getThoroughfare());
        placemark.put("subThoroughfare", address.getSubThoroughfare());
        placemark.put("postalCode", address.getPostalCode());
        placemark.put("administrativeArea", address.getAdminArea());
        placemark.put("subAdministrativeArea", address.getSubAdminArea());
        placemark.put("locality", address.getLocality());
        placemark.put("subLocality", address.getSubLocality());
```

Can you point us to the right documentation of information that we are missing?

Kind regards,
