### ISSUE TITLE
Error: A non-null value must be returned since the return type 'List<Placemark>' doesn't allow null.

### ISSUE THREAD

**Issue by lbesiche** [Baseflow/flutter-geocoding#95]
## 🐛 Bug Report

Simply by importing the plugin I get this error message, anyone else experiencing this issue? :
"Error: A non-null value must be returned since the return type 'List<Placemark>' doesn't allow null."

**Flutter Version:** 2.10.5

**Platform:** 
- Android

**Comment by JeroenWeener** [comment]
Hi @lbesiche, thank you for reaching out!

This looks to be a NNBD issue. Are you experiencing this issue on Flutter 3 as well? Which version of the plugin are you using?
