### ISSUE TITLE
The type 'List' is declared with 0 type parameters, but 1 type arguments were given.

### ISSUE THREAD

**Issue by kitoga** [Baseflow/flutter-geocoding#96]
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by JeroenWeener** [comment]
Hi @kitoga, thank you for filing a bug report!

Could you tell us where you encountered the issue you mentioned? We cannot investigate further without any context regarding your issue.
