### ISSUE TITLE
Placemark to get current location address from longitude& latitute

### ISSUE THREAD

**Issue by kitoga** [Baseflow/flutter-geocoding#97]
## 🐛 Bug Report

The name 'Placemark' isn't a type so it can't be used as a type argument. 
Try correcting the name to an existing type, or defining a type named 'Placemark'.

The type 'List' is declared with 0 type parameters, but 1 type arguments were given. 

is there an explanation for this

**Comment by JeroenWeener** [comment]
Hi @kitoga, thank you for reaching out.

It is unclear to me what issue you are encountering. Could you provide us with some additional information?
