### ISSUE TITLE
getting Platform Exception

### ISSUE THREAD

**Issue by shihabmi7** [Baseflow/flutter-geocoding#98]
## 🐛 Bug Report

I am getting an error when moving camera on **Google Map** & calling **placemarkFromCoordinates** api in onCameraMove callback in GoogleMap widget. I got data successfully at beginning & getting error after 5-6 times successful api calling. I saw related issues posted here that mentioned that **google & apple** has limit daily quota limit to get address details in each apps i guess. But it is highly appreciated that share your opinion about the error what i am getting.

### Error Details

`2022-05-31 07:26:52.997234+0600 Runner[807:224485] flutter: PlatformException(IO_ERROR, Error Domain=kCLErrorDomain Code=2 "(null)", null, null)
`

### Reproduction steps
```
Future<void> onCameraMove(CameraPosition position) async {
    printData("onCameraMove: " +
        position.target.latitude.toString() +
        " " +
        position.target.longitude.toString());
    initialPosition = position.target;
    try {
      if (initialPosition != null) {
        List<Placemark> placeMark = await placemarkFromCoordinates(
            initialPosition.latitude, initialPosition.longitude,
            localeIdentifier: "en_US");

        if (placeMark.isNotEmpty) {
          pMark.value = placeMark[0];
          locationText.value = initialPosition.latitude.toString() +
              "," +
              initialPosition.longitude.toString();
          printData("Location text: " + locationText.value);
        }
      }
    } on PlatformException catch (e) {
      printData(e.toString());
    }
  }
````

```
GoogleMap(
              onCameraMove: controller.onCameraMove,
              zoomControlsEnabled: false,
              myLocationEnabled: true,
              onMapCreated: (GoogleMapController pController) {
                controller.mapController.complete(pController);
              },
              markers: {},
              mapType: MapType.normal,
              initialCameraPosition: controller.currentCameraPosition,
            ),
```

### Configuration

**Version: 2.0.4** 

**Platform:** 
- [*] :iphone 6 Plus: iOS 12.5.5
- [ ] :robot: Android

**Comment by batoul-alani** [comment]
I have the same problem, in version 2.0.5

**Comment by JeroenWeener** [comment]
Hi @shihabmi7! Thank you for filing this bug report.

Like you mentioned, this is most likely a result of your application hitting the rate limit.

The geocoding functionality is meant to be used on only a single or a couple of locations. The services exposed by Google and Apple have rate limiting in place, limiting the number of locations that can be resolved within a time span.

In your code, you are trying to resolve a location whenever the camera has moved. I am assuming that `onCameraMove` is called many times. Naturally, your application will hit the rate limit after a few seconds of moving.

Unfortunately, there is nothing we can do about the rate limit. If you require many calls to a geocoding backend, I suggest you use a different plugin. This will likely come with a pricing plan, however.
