### ISSUE TITLE
Getting addresses from the latitude and longitude in flutter.

### ISSUE THREAD

**Issue by Hyder-026** [Baseflow/flutter-geocoding#99]
Wanted to know that, is there any free packages from which we can get address from the given latitude and longitude in flutter without any pricing issues, as geocoding has raised some pricing issues and couldn't get addresses from it.
Thank you.

**Comment by AdamBridges** [comment]
I am wondering if this is what I am experiencing right now as I am unable to retrieve addresses using the `placemarkFromCoordinates()` function.

**Comment by JeroenWeener** [comment]
Hi @Hyder-026, @AdamBridges!

I am not sure if I understand the question. The geocoding plugin should be able to translate your coordinates to locations for free on both Android and iOS. You mention pricing issues. What exactly do you mean by that? There is rate limiting in place, where you can only request translations up to a certain number of times per time period.

There are alternative geocoding plugins on pub.dev, but they likely use rate limiting or require an account to charge per translation.
